<?php 
$query = $this->get('query');
$num = $this->get('num');

$query2 = $this->get('query2');
$num2 = $this->get('num2');

$query3 = $this->get('query3');
$num3 = $this->get('num3');

$query4 = $this->get('query4');
$num4 = $this->get('num4');
$row4 = $this->get('row4');

$roww = $this->get('roww');
$delete = $this->get('delete');

$roww2 = $this->get('roww2');
$delete2 = $this->get('delete2');

$roww3 = $this->get('roww3');
$delete3 = $this->get('delete3');

$roww4 = $this->get('roww4');
$delete4 = $this->get('delete4');

if (!isset($_GET['edit_site']) && !isset($_GET['delete_site']) && !isset($_GET['edit_delivery']) && !isset($_GET['delete_delivery']) && !isset($_GET['edit_admin']) && !isset($_GET['delete_admin']) && !isset($_GET['edit_directrix']) && !isset($_GET['delete_directrix'])) { ?>
<div>
    <a class="seting-tovar" href="<?php echo base_url .'settings/tovars'; ?>"><i class="fas fa-sliders-h"></i> Управління товарами</a>
</div> 
<div class="settings">  
    <div>
        <h2>Паролі до сайта</h2>
        <br/>
        <table>
            <tr class="table-top">
                <td>№</td>
                <td class="width-name">Логін</td>
                <td>Дата</td>
                <td>Дія</td>
            </tr>
            <?php if ($num) {
                while ($row = mysqli_fetch_array($query, MYSQLI_BOTH)) {
                    $date_format = date_format(date_create($row['date']), 'd.m.Y'); ?>
                    <tr>                
                        <td><?php echo $row['id']; ?></td>
                        <td class="width-name"><a href="<?php echo base_url .'settings?edit_site&id='.$row['id']; ?>"><?php echo $row['login'];?></a></td>
                        <td><?php echo $date_format; ?></td>
                        <td> <a href="<?php echo base_url .'settings?edit_site&id='.$row['id']; ?>" class="edit" title="Змінити пароль"> <i class="fas fa-pen"></i></a> <a href="<?php echo base_url .'settings?delete_site&id='.$row['id']; ?>" class="delete" title="Видалити пароль"><i class="fas fa-trash-alt"></i></a></td>
                        <?php } } ?>
                    </tr>
                </table>
                <a href="<?php echo base_url .'settings/add_users?site'; ?>" class="add-tovar" title="Додати користувача"><i class="fas fa-plus"></i></a>
            </div>

            <div>
                <h2>Паролі до сторінки доставки</h2>
                <br/>
                <table>
                    <tr class="table-top">
                        <td>№</td>
                        <td class="width-name">Логін</td>
                        <td>Дата</td>
                        <td>Дія</td>
                    </tr>
            <?php if ($num2) {
                while ($row2 = mysqli_fetch_array($query2, MYSQLI_BOTH)) {
                    $date_format2 = date_format(date_create($row2['date']), 'd.m.Y'); ?>
                    <tr>                
                        <td><?php echo $row2['id']; ?></td>
                        <td class="width-name"><a href="<?php echo base_url .'settings?edit_delivery&id='.$row2['id']; ?>"><?php echo $row2['login'];?></a></td>
                        <td><?php echo $date_format2; ?></td>
                        <td> <a href="<?php echo base_url .'settings?edit_delivery&id='.$row2['id']; ?>" class="edit" title="Змінити пароль"> <i class="fas fa-pen"></i></a> <a href="<?php echo base_url .'settings?delete_delivery&id='.$row2['id']; ?>" class="delete" title="Видалити пароль"><i class="fas fa-trash-alt"></i></a></td>
                        <?php } } ?>
                    </tr>
                    </table>
                    <a href="<?php echo base_url .'settings/add_users?delivery'; ?>" class="add-tovar" title="Додати користувача"><i class="fas fa-plus"></i></a>
                </div>

                <div>
                    <h2>Паролі до адмінпанелі</h2>
                    <br/>
                    <table>
                        <tr class="table-top">
                            <td>№</td>
                            <td class="width-name">Логін</td>
                            <td>Точка</td>
                            <td>Дата</td>
                            <td>Дія</td>
                        </tr>
            <?php if ($num3) {
                while ($row3 = mysqli_fetch_array($query3, MYSQLI_BOTH)) {
                    $date_format3 = date_format(date_create($row3['date']), 'd.m.Y');
                    switch ($row3['tochka']) {
                         case 'bochka':
                             $tochka = 'Бочка';
                             break;
                         case 'center':
                             $tochka = 'Центр';
                             break;   
                     } ?>
                    <tr>                
                        <td><?php echo $row3['id']; ?></td>
                        <td class="width-name"><a href="<?php echo base_url .'settings?edit_admin&id='.$row3['id']; ?>"><?php echo $row3['login'];?></a></td>
                        <td><?php echo $tochka; ?></td>
                        <td><?php echo $date_format3; ?></td>
                        <td> <a href="<?php echo base_url .'settings?edit_admin&id='.$row3['id']; ?>" class="edit" title="Змінити пароль"> <i class="fas fa-pen"></i></a> <a href="<?php echo base_url .'settings?delete_admin&id='.$row3['id']; ?>" class="delete" title="Видалити пароль"><i class="fas fa-trash-alt"></i></a></td>
                        <?php } } ?>
                    </tr>
                        </table>
                        <a href="<?php echo base_url .'settings/add_users?admin'; ?>" class="add-tovar" title="Додати користувача"><i class="fas fa-plus"></i></a>
                    </div>

                    <div>
                        <h2>Паролі до дирекції</h2>
                        <br/>
                        <table>
                            <tr  class="table-top">
                                <td>№</td>
                                <td class="width-name">Логін</td>
                                <td>Дата</td>
                                <td>Дія</td>
                            </tr>
            <?php if ($num4) {
                while ($row4 = mysqli_fetch_array($query4, MYSQLI_BOTH)) {
                    $date_format4 = date_format(date_create($row4['date']), 'd.m.Y'); ?>
                    <tr>                
                        <td><?php echo $row4['id']; ?></td>
                        <td class="width-name"><a href="<?php echo base_url .'settings?edit_directrix&id='.$row4['id']; ?>"><?php echo $row4['login'];?></a></td>
                        <td><?php echo $date_format4; ?></td>
                        <td> <a href="<?php echo base_url .'settings?edit_directrix&id='.$row4['id']; ?>" class="edit" title="Змінити пароль"> <i class="fas fa-pen"></i></a> <a href="<?php echo base_url .'settings?delete_directrix&id='.$row4['id']; ?>" class="delete" title="Видалити пароль"><i class="fas fa-trash-alt"></i></a></td>
                        <?php } } ?>
                    </tr>
                            </table>
                            <a href="<?php echo base_url .'settings/add_users?directrix'; ?>" class="add-tovar" title="Додати користувача"><i class="fas fa-plus"></i></a>
                        </div>


                        <?php
                    } else { 

                        if (isset($_GET['edit_site'])) {
                            $errore = $this->get('errore');
                            ?>
                            <div>
                                <?php 
                                if (!empty($errore)) echo "<div style='color: red;  float: right;'>" .$errore ."</div>"; ?>
                                </div>
                                <div>
                                    <h3>Змінити пароль</h3>
                                    <form action="<?php echo base_url .'settings?edit_site&id='.$roww['id']; ?>" method="post">
                                        <table class="add-table">
                                            <tr class="table-top">
                                                <td>№</td>
                                                <td class="width-name">Логін</td>
                                                <td>Новий пароль</td>
                                                <td>Пітвердження пароля</td>
                                            </tr>
                                            <tr>
                                                <td> <?php echo $roww['id']; ?></td>
                                                <td><?php echo $roww['login']; ?></td>
                                                <td> <input type="password" name="password"> </td>
                                                <td> <input type="password" name="password-confirm"> </td>             
                                            </tr>
                                            <input class="sub-save" type="submit" name="save" value=" Зберегти">
                                        </table>
                                        <br/><br/><br/><br/><br/>

                                    </form>
                                    <?php
                                }

                                if (isset($_GET['delete_site'])) {
                                            if (!isset($delete)) {
                                                 ?>
                                            <div class="delete-block-top zatmenie">
                                                <div class="delete-block">
                                                    <form action="<?php echo base_url .'settings?delete_site&id='.$roww['id']; ?>" method="post">
                                                        Ви дійсно хочете <span style="color: red;">видалити</span> даного користувача!!!<br/><br/>
                                                        <button type="submit" class="confirmation-btn" name="delete_user" value="1">Так</button>
                                                        <button type="submit" class="confirmation-btn" name="delete_user" value="0">Ні</button>
                                                    </form>
                                                </div>
                                            </div>

                                            <?php  } else {
                                                echo "<div style='color: green;'>Користувача успішно видалено!</div>";
                                            }

                                        }

                                if (isset($_GET['edit_delivery'])) {
                            $errore2 = $this->get('errore2');
                            ?>
                            <div>
                                <?php 
                                if (!empty($errore2)) echo "<div style='color: red; float: right;'>" .$errore2 ."</div>"; ?>
                                </div>
                                <div>
                                    <h3>Змінити пароль</h3>
                                    <form action="<?php echo base_url .'settings?edit_delivery&id='.$roww2['id']; ?>" method="post">
                                        <table class="add-table">
                                            <tr class="table-top">
                                                <td>№</td>
                                                <td class="width-name">Логін</td>
                                                <td>Новий пароль</td>
                                                <td>Пітвердження пароля</td>
                                            </tr>
                                            <tr>
                                                <td> <?php echo $roww2['id']; ?></td>
                                                <td><?php echo $roww2['login']; ?></td>
                                                <td> <input type="password" name="password"> </td>
                                                <td> <input type="password" name="password-confirm"> </td>             
                                            </tr>
                                            <input class="sub-save" type="submit" name="save" value=" Зберегти">
                                        </table>
                                        <br/><br/><br/><br/><br/>

                                    </form>
                                    <?php
                                }

                                if (isset($_GET['delete_delivery'])) {
                                            if (!isset($delete2)) {
                                                 ?>
                                            <div class="delete-block-top zatmenie">
                                                <div class="delete-block">
                                                    <form action="<?php echo base_url .'settings?delete_delivery&id='.$roww2['id']; ?>" method="post">
                                                        Ви дійсно хочете <span style="color: red;">видалити</span> даного користувача!!!<br/><br/>
                                                        <button type="submit" class="confirmation-btn" name="delete_user" value="1">Так</button>
                                                        <button type="submit" class="confirmation-btn" name="delete_user" value="0">Ні</button>
                                                    </form>
                                                </div>
                                            </div>

                                            <?php  } else {
                                                echo "<div style='color: green;'>Користувача успішно видалено!</div>";
                                            }

                                        }

                                    if (isset($_GET['edit_admin'])) {
                            $errore3 = $this->get('errore3');
                            ?>
                            <div>
                                <?php 
                                if (!empty($errore3)) echo "<div style='color: red; float: right;'>" .$errore3 ."</div>"; ?>
                                </div>
                                <div>
                                    <h3>Змінити пароль</h3>
                                    <form action="<?php echo base_url .'settings?edit_admin&id='.$roww3['id']; ?>" method="post">
                                        <table class="add-table">
                                            <tr class="table-top">
                                                <td>№</td>
                                                <td class="width-name">Логін</td>
                                                <td>Новий пароль</td>
                                                <td>Пітвердження пароля</td>
                                            </tr>
                                            <tr>
                                                <td> <?php echo $roww3['id']; ?></td>
                                                <td><?php echo $roww3['login']; ?></td>
                                                <td> <input type="password" name="password"> </td>
                                                <td> <input type="password" name="password-confirm"> </td>             
                                            </tr>
                                            <input class="sub-save" type="submit" name="save" value=" Зберегти">
                                        </table>
                                        <br/><br/><br/><br/><br/>

                                    </form>
                                    <?php
                                }

                                if (isset($_GET['delete_admin'])) {
                                            if (!isset($delete3)) {
                                                 ?>
                                            <div class="delete-block-top zatmenie">
                                                <div class="delete-block">
                                                    <form action="<?php echo base_url .'settings?delete_admin&id='.$roww3['id']; ?>" method="post">
                                                        Ви дійсно хочете <span style="color: red;">видалити</span> даного користувача!!!<br/><br/>
                                                        <button type="submit" class="confirmation-btn" name="delete_user" value="1">Так</button>
                                                        <button type="submit" class="confirmation-btn" name="delete_user" value="0">Ні</button>
                                                    </form>
                                                </div>
                                            </div>

                                            <?php  } else {
                                                echo "<div style='color: green;'>Користувача успішно видалено!</div>";
                                            }

                                        }

                                        if (isset($_GET['edit_directrix'])) {
                            $errore4 = $this->get('errore4');
                            ?>
                            <div>
                                <?php 
                                if (!empty($errore4)) echo "<div style='color: red; float: right;'>" .$errore4 ."</div>"; ?>
                                </div>
                                <div>
                                    <h3>Змінити пароль</h3>
                                    <form action="<?php echo base_url .'settings?edit_directrix&id='.$roww4['id']; ?>" method="post">
                                        <table class="add-table">
                                            <tr class="table-top">
                                                <td>№</td>
                                                <td class="width-name">Логін</td>
                                                <td>Новий пароль</td>
                                                <td>Півердження пароля</td>
                                            </tr>
                                            <tr>
                                                <td> <?php echo $roww4['id']; ?></td>
                                                <td><?php echo $roww4['login']; ?></td>
                                                <td> <input type="password" name="password"> </td>
                                                <td> <input type="password" name="password-confirm"> </td>             
                                            </tr>
                                            <input class="sub-save" type="submit" name="save" value=" Зберегти">
                                        </table>
                                        <br/><br/><br/><br/><br/>

                                    </form>
                                    <?php
                                }

                                if (isset($_GET['delete_directrix'])) {
                                            if (!isset($delete4)) {
                                                 ?>
                                            <div class="delete-block-top zatmenie">
                                                <div class="delete-block">
                                                    <form action="<?php echo base_url .'settings?delete_directrix&id='.$roww4['id']; ?>" method="post">
                                                        Ви дійсно хочете <span style="color: red;">видалити</span> даного користувача!!!<br/><br/>
                                                        <button type="submit" class="confirmation-btn" name="delete_user" value="1">Так</button>
                                                        <button type="submit" class="confirmation-btn" name="delete_user" value="0">Ні</button>
                                                    </form>
                                                </div>
                                            </div>

                                            <?php  } else {
                                                echo "<div style='color: green;'>Користувача успішно видалено!</div>";
                                            }

                                        }

                                    }
                                    ?>
                                </div> 