<?php $current = $_SERVER['REQUEST_URI']; ?>
<div class="delivery-block-menu">
	<span><a class="<?php if($current == '/delivery/bochka' 
	|| $current == '/delivery/bochka?tovar=fruits' 
	|| $current == '/delivery/bochka?tovar=vegetables' 
	|| $current == '/delivery/bochka?tovar=sausage' 
	|| $current == '/delivery/bochka?tovar=cheese' 
	|| $current == '/delivery/bochka?tovar=fish_processing' 
	|| $current == '/delivery/bochka?tovar=fish_sm' 
	|| $current == '/delivery/bochka?tovar=ovis' 
	|| $current == '/delivery/bochka?tovar=radema'): ?>current<?php endif; ?>" href="<?php echo base_url .'delivery/bochka';?>">Бочка</a></span>
	<span><a class="<?php if($current == '/delivery/fish_terminal' 
	|| $current == '/delivery/fish_terminal?tovar=fruits' 
	|| $current == '/delivery/fish_terminal?tovar=vegetables' 
	|| $current == '/delivery/fish_terminal?tovar=sausage' 
	|| $current == '/delivery/fish_terminal?tovar=cheese' 
	|| $current == '/delivery/fish_terminal?tovar=fish_processing' 
	|| $current == '/delivery/fish_terminal?tovar=fish_sm' 
	|| $current == '/delivery/fish_terminal?tovar=ovis' 
	|| $current == '/delivery/fish_terminal?tovar=radema'): ?>current<?php endif; ?>" href="<?php echo base_url .'delivery/fish_terminal';?>">Рибний термінал</a></span>
	<span><a class="<?php if($current == '/delivery/gurtovnya' 
	|| $current == '/delivery/gurtovnya?tovar=fruits' 
	|| $current == '/delivery/gurtovnya?tovar=vegetables' 
	|| $current == '/delivery/gurtovnya?tovar=sausage' 
	|| $current == '/delivery/gurtovnya?tovar=cheese' 
	|| $current == '/delivery/gurtovnya?tovar=fish_processing' 
	|| $current == '/delivery/gurtovnya?tovar=fish_sm' 
	|| $current == '/delivery/gurtovnya?tovar=ovis' 
	|| $current == '/delivery/gurtovnya?tovar=radema'): ?>current<?php endif; ?>" href="<?php echo base_url .'delivery/gurtovnya';?>">Гуртовня</a></span>
	<span><a class="<?php if($current == '/delivery/center' 
	|| $current == '/delivery/center?tovar=fruits' 
	|| $current == '/delivery/center?tovar=vegetables' 
	|| $current == '/delivery/center?tovar=sausage' 
	|| $current == '/delivery/center?tovar=cheese' 
	|| $current == '/delivery/center?tovar=fish_processing' 
	|| $current == '/delivery/center?tovar=fish_sm' 
	|| $current == '/delivery/center?tovar=ovis' 
	|| $current == '/delivery/center?tovar=radema'): ?>current<?php endif; ?>" href="<?php echo base_url .'delivery/center';?>">Центр</a></span>
	<span><a class="delivery-exit" href="<?php echo base_url .'delivery/logout'; ?>">Вихід</a></span>
</div>