<div class="distribution-block">
	
	<table>
		<tr class="table-top">
			<td>№</td>
			<td class="width-name">Назва</td>
			<td>Бочка</td>
			<td>Рибний термінал</td>
			<td>Гуртовня</td>
			<td>Центр</td>
			<td>Кількість доставки</td>
			<td>Кількість Кг</td>
			<td>Дія</td>
		</tr>
		<tr>
			<td><?php echo['']; ?></td>
			<td><?php echo['']; ?></td>
			<td><?php echo['']; ?></td>
			<td><?php echo['']; ?></td>
			<td><?php echo['']; ?></td>
			<td><?php echo['']; ?></td>
			<td><?php echo['']; ?></td>
			<td><?php echo['']; ?></td>
			<td><a href="<?php echo base_url .$table .'?edit&id='.$row2['id']; ?>" class="edit" title="Внести Кг"> <i class="fas fa-pen"></i></a></td>
		</tr>
	</table>
</div>