<div style="text-align: center; margin-top: 200px;">
	<p><i style="color: #000; font-size: 30px;" class="fas fa-wrench"></i></p>
	На даний момент ця сторінка в розробці </br>
	<h3>Очікуйте...</h3>
</div>


<!-- <div class="distribution-block">
	
	<table>
		<tr class="table-top">
			<td>№</td>
			<td class="width-name">Назва</td>
			<td>Бочка</td>
			<td>Рибний термінал</td>
			<td>Гуртовня</td>
			<td>Центр</td>
			<td>Кількість доставки</td>
			<td>Кількість Кг</td>
			<td>Дія</td>
		</tr>
		<tr>
			<td><?php echo['']; ?></td>
			<td><?php echo['']; ?></td>
			<td><?php echo['']; ?></td>
			<td><?php echo['']; ?></td>
			<td><?php echo['']; ?></td>
			<td><?php echo['']; ?></td>
			<td><?php echo['']; ?></td>
			<td><?php echo['']; ?></td>
			<td><a href="<?php echo base_url .$table .'?edit&id='.$row2['id']; ?>" class="edit" title="Внести Кг"> <i class="fas fa-pen"></i></a></td>
		</tr>
	</table>
</div> -->