<?php $current = $_SERVER['REQUEST_URI']; ?>
<div class="head">
	<div class="dostavka-head">
		<a href="<?php echo base_url .'index_authorization/logout';?>">Вихід</a>
	</div>
	<div class="dostavka-head">
		<a class="<?php if($current == '/admin/settings_tovars'): ?>current<?php endif; ?>" href="<?php echo base_url .'settings_tovars';?>"><i class="fas fa-cog"></i></a>
	</div>
	<div class="search-head">
		<form action="<?php echo base_url .'search';?>" method="get">
			<input class="search-form srch" type="search" name="search_query" placeholder=" введіть ваш запит"/>
			<input class="search-btn srch" type="submit" name="search" value="знайти" />
		</form>
		
	</div>
	<div class="dostavka-head">
		<a class="<?php if($current == '/admin/purchase'): ?>current<?php endif; ?>" href="<?php echo base_url .'purchase';?>">Закупка</a>
	</div>
	<div class="dostavka-head purchase">
		<a class="<?php if($current == '/admin/distribution'
		 || $current == '/admin/distribution/bochka' 
	|| $current == '/admin/distribution/bochka?tovar=fruits' 
	|| $current == '/admin/distribution/bochka?tovar=vegetables' 
	|| $current == '/admin/distribution/bochka?tovar=sausage' 
	|| $current == '/admin/distribution/bochka?tovar=cheese' 
	|| $current == '/admin/distribution/bochka?tovar=fish_processing' 
	|| $current == '/admin/distribution/bochka?tovar=fish_sm' 
	|| $current == '/admin/distribution/bochka?tovar=ovis' 
	|| $current == '/admin/distribution/bochka?tovar=radema'
	|| $current == '/admin/distribution/fish_terminal' 
	|| $current == '/admin/distribution/fish_terminal?tovar=fruits' 
	|| $current == '/admin/distribution/fish_terminal?tovar=vegetables' 
	|| $current == '/admin/distribution/fish_terminal?tovar=sausage' 
	|| $current == '/admin/distribution/fish_terminal?tovar=cheese' 
	|| $current == '/admin/distribution/fish_terminal?tovar=fish_processing' 
	|| $current == '/admin/distribution/fish_terminal?tovar=fish_sm' 
	|| $current == '/admin/distribution/fish_terminal?tovar=ovis' 
	|| $current == '/admin/distribution/fish_terminal?tovar=radema'
	|| $current == '/admin/distribution/gurtovnya' 
	|| $current == '/admin/distribution/gurtovnya?tovar=fruits' 
	|| $current == '/admin/distribution/gurtovnya?tovar=vegetables' 
	|| $current == '/admin/distribution/gurtovnya?tovar=sausage' 
	|| $current == '/admin/distribution/gurtovnya?tovar=cheese' 
	|| $current == '/admin/distribution/gurtovnya?tovar=fish_processing' 
	|| $current == '/admin/distribution/gurtovnya?tovar=fish_sm' 
	|| $current == '/admin/distribution/gurtovnya?tovar=ovis' 
	|| $current == '/admin/distribution/gurtovnya?tovar=radema'
	|| $current == '/admin/distribution/center' 
	|| $current == '/admin/distribution/center?tovar=fruits' 
	|| $current == '/admin/distribution/center?tovar=vegetables' 
	|| $current == '/admin/distribution/center?tovar=sausage' 
	|| $current == '/admin/distribution/center?tovar=cheese' 
	|| $current == '/admin/distribution/center?tovar=fish_processing' 
	|| $current == '/admin/distribution/center?tovar=fish_sm' 
	|| $current == '/admin/distribution/center?tovar=ovis' 
	|| $current == '/admin/distribution/center?tovar=radema'
	|| $current == '/admin/distribution/invoice' 
	|| $current == '/admin/distribution/invoice?tovar=fruits' 
	|| $current == '/admin/distribution/invoice?tovar=vegetables' 
	|| $current == '/admin/distribution/invoice?tovar=sausage' 
	|| $current == '/admin/distribution/invoice?tovar=cheese' 
	|| $current == '/admin/distribution/invoice?tovar=fish_processing'
	|| $current == '/admin/distribution/invoice?tovar=fish_sm' 
	|| $current == '/admin/distribution/invoice?tovar=ovis' 
	|| $current == '/admin/distribution/invoice?tovar=radema'): ?>current<?php endif; ?>" href="<?php echo base_url .'distribution';?>">Розприділення</a>
	</div>

</div>