<?php $current = $_SERVER['REQUEST_URI']; ?>
<div class="head">
	<div class="dostavka-head">
		<a href="<?php echo base_url .'index_authorization/logout';?>">Вихід</a>
	</div>
	<div class="search-head">
		<form action="<?php echo base_url .'search';?>" method="get">
			<input class="search-form srch" type="search" name="search_query" placeholder=" введіть ваш запит"/>
			<input class="search-btn srch" type="submit" name="search" value="знайти" />
		</form>
		
	</div>
	<div class="dostavka-head">
		<a class="<?php if($current == '/admin/purchase'): ?>current<?php endif; ?>" href="<?php echo base_url .'purchase';?>">Закупка</a>
	</div>
	<div class="dostavka-head purchase">
		<a href="/distribution">Розприділення</a>
	</div>
</div>