 <!DOCTYPE html>
 <html lang="ua">
 <head>
 	<meta charset="UTF-8">
 	<title>АдмінПанель</title>
 	<link rel="stylesheet" href="../styles/authorization.css" media="screen">
 </head>
 <body>
 	    <?php 
    if (!isset($_SESSION['login_admin'])) {            
        ?>
 <div class="authorization-block">
 	
 	 	<p>Вхід в Директорію</p>
 	<h1><img src="../img/logo.png" alt="Гуртова База"></h1>

 	<form action="/admin/index_authorization" method="post">
 		<input type="text" name="login" placeholder=" логін"/><br/><br/>
 		<input type="password" name="password" placeholder=" пароль"/><br/><br/>
 		<input type="submit"/ name="log" value="Увійти">
 	</form>
 </div>
 <?php }
 else {
 	header("Location: /admin");
 } ?>
 </body>
 </html>