<?php 
$errore = $this->get('errore');
 ?>
 <div>
 	<?php 
 	if (!empty($errore)) echo "<div style='color: red;'>" .$errore ."</div>"; 
 	if (empty($errore)) {
		if (!empty($_POST)) {
			echo "<div style='color: green;'>Товар \"".$_POST['name_tovar']."\" успішно доданий!</div>";
		}
	}
 	?>
 </div>
<div>
	<form action="<?php echo base_url .'add';?>" method="post">
		<table class="add-table">
			<tr class="table-top">
				<td class="width-name">Назва</td>
				<td>Бочка</td>
				<td>Рибний турмінал</td>
				<td>Гуртовня</td>
				<td>Центр</td>
			</tr>
			<tr>
				<td> <input type="text" name="name_tovar" value="<?php echo @$_POST['name_tovar']; ?>"> </td>
				<td> <input type="number" name="bochka_tovar" step="0.1" value="<?php echo @$_POST['bochka_tovar']; ?>"> </td>
				<td> <input type="number" name="fish_tovar" step="0.1" value="<?php echo @$_POST['fish_tovar']; ?>"> </td>
				<td> <input type="number" name="gyrtovna_tovar" step="0.1" value="<?php echo @$_POST['gyrtovna_tovar']; ?>"> </td>
				<td> <input type="number" name="centr_tovar" step="0.1" value="<?php echo @$_POST['centr_tovar']; ?>"> </td>			
			</tr>
				<input class="sub-save" type="submit" name="add" value=" Зберегти">
		</table>
		<input type="hidden" name="date" value="<?php echo date('Y-m-d') ?>" />
		<br/><br/><br/><br/><br/>
		
	
	</form>
</div>