<div class="content">	
	<div class="dostavka">	
		<h2>Фрукти</h2>
		<ul>
			<li><input type="checkbox" class="checkbox" id="banan" />
<label for="banan">Банани</label><input type="text" placeholder=" Кількість"></li>
			<li>	<input type="checkbox" class="checkbox" id="apelsin" />
<label for="apelsin">Апeльсини</label><input type="text" placeholder=" Кількість"></li>
			<li>	<input type="checkbox" class="checkbox" id="limon" />
<label for="limon">Лимони</label><input type="text" placeholder=" Кількість"></li>
			<li>	<input type="checkbox" class="checkbox" id="laim" />
<label for="laim">Лайм</label><input type="text" placeholder=" Кількість"></li>
			<li>	<input type="checkbox" class="checkbox" id="greypfruit" />
<label for="greypfruit">Грейпфрукт</label><input type="text" placeholder=" Кількість"></li>
			<li>	<input type="checkbox" class="checkbox" id="kivi" />
<label for="kivi">Ківі</label><input type="text" placeholder=" Кількість"></li>
			<li>	<input type="checkbox" class="checkbox" id="ananas big" />
<label for="ananas big">Ананас вел.</label><input type="text" placeholder=" Кількість"></li>
			<li>	<input type="checkbox" class="checkbox" id="ananas small" />
<label for="ananas small">Ананас мал.</label><input type="text" placeholder=" Кількість"></li>
			<li>	<input type="checkbox" class="checkbox" id="granat" />
<label for="granat">Гранат</label><input type="text" placeholder=" Кількість"></li>
			<li>	<input type="checkbox" class="checkbox" id="imbir" />
<label for="imbir">Імбир ваг.</label><input type="text" placeholder=" Кількість"></li>
			<li>	<input type="checkbox" class="checkbox" id="grusha" />
<label for="grusha">Груша</label><input type="text" placeholder=" Кількість"></li>
			<li>	<input type="checkbox" class="checkbox" id="persik" />
<label for="persik">Персик:3</label><input type="text" placeholder=" Кількість"></li>
			<li>	<input type="checkbox" class="checkbox" id="nektarin" />
<label for="nektarin">Нектарин:3</label><input type="text" placeholder=" Кількість"></li>
			<li>	<input type="checkbox" class="checkbox" id="abrikos" />
<label for="abrikos">Абрикос</label><input type="text" placeholder=" Кількість"></li>
			<li>	<input type="checkbox" class="checkbox" id="sliva" />
<label for="sliva">Слива:2</label><input type="text" placeholder=" Кількість"></li>
			<li>	<input type="checkbox" class="checkbox" id="vinograd" />
<label for="vinograd">Виноград:3</label><input type="text" placeholder=" Кількість"></li>
			<li>	<input type="checkbox" class="checkbox" id="chereshnya" />
<label for="chereshnya">Черешня:2</label><input type="text" placeholder=" Кількість"></li>
			<li>	<input type="checkbox" class="checkbox" id="yabluko" />
<label for="yabluko">Яблуко:</label><input type="text" placeholder=" Кількість"></li>
		</ul>
		<h2>Сухофрукти</h2>
		<ul>
			<li><input type="checkbox" class="checkbox" id="izym" />
<label for="izym">Ізюм</label></li>
			<li><input type="checkbox" class="checkbox" id="chornosliv vyal" />
<label for="chornosliv vyal">Чорнослив в'ялений</label></li>
			<li><input type="checkbox" class="checkbox" id="chornosliv kopch" />
<label for="chornosliv kopch">Чорнослив копчений</label></li>
			<li><input type="checkbox" class="checkbox" id="kuraga" />
<label for="kuraga">Курага</label></li>
			<li><input type="checkbox" class="checkbox" id="finiki" />
<label for="finiki">Фініки</label></li>
			<li><input type="checkbox" class="checkbox" id="ingir" />
<label for="ingir">Інжир</label></li>
			<li><input type="checkbox" class="checkbox" id="cukaty" />
<label for="cukaty">Цукати</label></li>
			<li><input type="checkbox" class="checkbox" id="sushka" />
<label for="sushka">Сушка</label></li>
		</ul>
		<h2>Овочі</h2>
		ul>li*
	</div>
</div>