<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<link rel="stylesheet" href="../styles/authorization.css">
</head>
<body class="delivery">	
	

	<?php 
	$errorsl = $this->get('errorsl');
	$errore = $this->get('errore');

	if (!isset($_SESSION['login_delivery'])) {            
		?>
		<div class="authorization-delivery">
			<?php if (!empty($errorsl)) { ?>
			<div>
				<span style="color:red	;"><?php echo $errorsl; ?></span>
			</div> 
			<?php } ?>
			<p>Вхід на сторінку доставки</p>
			<br/>
			<form action="<?php echo base_url .'delivery'; ?>" method="post">
				<input class="delivery-int" type="text" name="login" placeholder=" ваш логін" value="<?php echo @$_POST['login']; ?>" /><br/><br/>
				<input class="delivery-int" type="password" name="password" placeholder=" ваш пароль"/><br/><br/>
				<input type="submit" name="log" value="Увійти" />
			</form>
		</div>
		<?php }
		else { ?>

		<div class="delivery-block-menu">
			<span><a href="<?php echo base_url .'delivery/bochka';?>">Бочка</a></span>
			<span><a href="<?php echo base_url .'delivery/fish_terminal';?>">Рибний термінал</a></span>
			<span><a href="<?php echo base_url .'delivery/gurtovnya';?>">Гуртовня</a></span>
			<span><a href="<?php echo base_url .'delivery/center';?>">Центр</a></span>
			<span><a class="delivery-exit" href="<?php echo base_url .'delivery/logout'; ?>">Вихід</a></span>
		</div>

		<a href="#x" class="overlay" id="errore"></a>
		<div class="popup">
			<div>
				<span style="color:red	;"><?php echo $errore; ?></span>		
			</div> 
			<a class="close" title="Закрыть" href="#close"></a>
		</div>
		<?php if (!empty($errore)) {
		header("Location:" .base_url .'delivery#errore');
		} ?>
		<form action="<?php echo base_url .'delivery';?>" method="post">
			<input class="sub-reset" type="reset" value="Скинути" title="Скинути введення">
			<div class="dostavka">	
				<h2>Фрукти</h2>
				<ul>
					<li>
						<label for="banan">Банан</label><input type="number" name="fruits[1]" step="0.1" placeholder=" Кількість">
					</li>
					<li>	
						<label for="apelsin">Апeльсин</label><input type="number" step="0.1" name="fruits[2]" placeholder=" Кількість" >
					</li>
					<li>	
						<label for="limon">Лимон</label><input type="number" step="0.1" name="fruits[3]" placeholder=" Кількість" >
					</li>
					<li>	
						<label for="laim">Лайм</label><input type="number" step="0.1" name="fruits[4]" placeholder=" Кількість" >
					</li>
					<li>	
						<label for="greypfruit">Грейпфрукт</label><input type="number" step="0.1" name="fruits[5]"  placeholder=" Кількість">
					</li>
					<li>	
						<label for="kivi">Ківі</label><input type="number" step="0.1" name="fruits[6]" placeholder=" Кількість">
					</li>
					<li>	
						<label for="ananas-big">Ананас вел.</label><input type="number" step="0.1" name="fruits[7]" placeholder=" Кількість" >
					</li>
					<li>	
						<label for="ananas-small">Ананас мал.</label><input type="number" step="0.1" name="fruits[8]" placeholder=" Кількість" >
					</li>
					<li>	
						<label for="granat">Гранат</label><input type="number" step="0.1" name="fruits[9]" placeholder=" Кількість" >
					</li>
					<li>	
						<label for="grusha">Груша</label><input type="number" step="0.1" name="fruits[10]" placeholder=" Кількість" >
					</li>
					<li>	
						<label for="persik-red">Персик "Редхевен"</label><input type="number" step="0.1" name="fruits[11]" placeholder=" Кількість" >
					</li>
					<li>	
						<label for="persik-princ">Персик "Принц"</label><input type="number" step="0.1" name="fruits[12]" placeholder=" Кількість" >
					</li>
					<li>	
						<label for="persik-ingir">Персик "Інжирний"</label><input type="number" step="0.1" name="fruits[13]" placeholder=" Кількість" >
					</li>		
					<li>	
						<label for="nektarin-white">Нектарин "Світлий"</label><input type="number" step="0.1" name="fruits[14]" placeholder=" Кількість" >
					</li>
					<li>	
						<label for="nektarin-black">Нектарин "Темний"</label><input type="number" step="0.1" name="fruits[15]" placeholder=" Кількість" >
					</li>	
					<li>	
						<label for="abrikos">Абрикос</label><input type="number" step="0.1" name="fruits[16]" placeholder=" Кількість" >
					</li>
					<li>	
						<label for="sliva">Слива</label><input type="number" step="0.1" name="fruits[17]" placeholder=" Кількість" >
					</li>
					<li>	
						<label for="vinograd-kish">Виноград "Киш-Миш"</label><input type="number" step="0.1" name="fruits[18]" placeholder=" Кількість" >
					</li>
					<li>	
						<label for="vinograd-myskat">Виноград "Мускат"</label><input type="number" step="0.1" name="fruits[19]" placeholder=" Кількість" >
					</li>
					<li>	
						<label for="vinograd-arkadiya">Виноград "Аркадія"</label><input type="number" step="0.1" name="fruits[20]" placeholder=" Кількість" >
					</li>
					<li>	
						<label for="vinograd-kardinal">Виноград "Кардинал"</label><input type="number" step="0.1" name="fruits[21]" placeholder=" Кількість" >
					</li>
					<li>	
						<label for="vinograd-preob">Виноград "Преображеніє"</label><input type="number"step="0.1" name="fruits[22]" placeholder=" Кількість" >
					</li>
					<li>	
						<label for="vinograd-moldova">Виноград "Молдова"</label><input type="number" step="0.1" name="fruits[23]" placeholder=" Кількість" >
					</li>
					<li>	
						<label for="yabluko">Яблуко "Голден"</label><input type="number" step="0.1" name="fruits[24]" placeholder=" Кількість" >
					</li>
				</ul>
				<h2>Сухофрукти</h2>
				<ul>
					<li>
						<label for="izym">Ізюм</label><input type="number" step="0.1" name="driedfruit[25]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="chornosliv-vyal">Чорнослив в'ялений</label><input type="number" step="0.1" name="driedfruit[26]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="kuraga">Курага</label><input type="number" step="0.1" name="driedfruit[27]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="finiki">Фініки</label><input type="number" step="0.1" name="driedfruit[28]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="ingir">Інжир</label><input type="number" step="0.1" name="driedfruit[29]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="cukaty">Цукати</label><input type="number" step="0.1" name="driedfruit[30]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="sushka">Сушка</label><input type="number" step="0.1" name="driedfruit[31]"  placeholder=" Кількість">
					</li>		
				</ul>
				<h2>Овочі</h2>
				<ul>
					<li>
						<label for="grib">Гриб</label><input type="number" step="0.1" name="vegetables[32]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="imbir">Імбир</label><input type="number" step="0.1" name="vegetables[33]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="ogirok-kornishok">Огірок "Корнішок"</label><input type="number" step="0.1" name="vegetables[34]" placeholder=" Кількість">
					</li>
					<li>
						<label for="krip">Кріп</label><input type="number" step="0.1" name="vegetables[35]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="petrushka">Петрушка</label><input type="number" step="0.1" name="vegetables[36]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="salat-green">Салат зелений</label><input type="number" step="0.1" name="vegetables[37]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="avokado">Авокадо</label><input type="number" step="0.1" name="vegetables[38]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="ayzberg">Айзберг</label><input type="number" step="0.1" name="vegetables[39]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="rukola">Рукола</label><input type="number" step="0.1" name="vegetables[40]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="pomidor-krug">Помідор "Круглий"</label><input type="number" step="0.1" name="vegetables[41]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="pomidor-sliva">Помідор "Сливочка"</label><input type="number" step="0.1" name="vegetables[42]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="pomidor-yellow">Помідор жовтий</label><input type="number" step="0.1" name="vegetables[43]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="pomidor-red">Помідор червоний</label><input type="number" step="0.1" name="vegetables[44]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="pomidor-blackprinc">Помідор "Чорний принц"</label><input type="number" step="0.1" name="vegetables[45]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="pomidor-sokal">Помідор "Сокаль"</label><input type="number" step="0.1" name="vegetables[46]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="pomidor-zorya">Помідор "Зоря"</label><input type="number" step="0.1" name="vegetables[47]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="pomidor-cheri">Помідор "Чері"</label><input type="number" step="0.1" name="vegetables[48]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="pomidor-kokteyl">Помідор "Коктейль"</label><input type="number" step="0.1" name="vegetables[49]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="baklazhan">Баклажан</label><input type="number" step="0.1" name="vegetables[50]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="perec-herson">Перець херсон</label><input type="number" step="0.1" name="vegetables[51]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="perec-red">Перець червоний</label><input type="number" step="0.1" name="vegetables[52]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="perec-yellow">Перець жовтий</label><input type="number" step="0.1" name="vegetables[53]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="chasnik">Часник</label><input type="number" step="0.1" name="vegetables[54]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="kapusta-bilock">Капуста "Білок."</label><input type="number" step="0.1" name="vegetables[55]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="kapusta-cvitna">Капуста "Цвітна"</label><input type="number" step="0.1" name="vegetables[56]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="kapusta-pekinska">Капуста "Пекінська"</label><input type="number" step="0.1" name="vegetables[57]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="kapusta-brokoli">Капуста "Броколі"</label><input type="number" step="0.1" name="vegetables[58]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="morkva">Морква</label><input type="number" step="0.1" name="vegetables[59]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="kartoplya">Картопля</label><input type="number" step="0.1" name="vegetables[60]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="buryak">Буряк</label><input type="number" step="0.1" name="vegetables[61]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="cibulya">Цибуля</label><input type="number" step="0.1" name="vegetables[62]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="perec-chili">Перець чилі</label><input type="number" step="0.1" name="vegetables[63]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="cibulya-yalta">Цибуля "Ялта"</label><input type="number" step="0.1" name="vegetables[64]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="cibulya-white">Цибуля біла</label><input type="number" step="0.1" name="vegetables[65]"  placeholder=" Кількість">
					</li>				
				</ul>
				<h2>Ковбаса</h2>
				<ul>
					<li>
						<label for="soyuzna">Союзна</label><input type="number" step="0.1" name="sausage[66]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="originalna">Оригінальна</label><input type="number" step="0.1" name="sausage[67]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="minska">Мінська</label><input type="number" step="0.1" name="sausage[68]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="ryadyanska">Радянська</label><input type="number" step="0.1" name="sausage[69]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="ekstra">Екстра</label><input type="number" step="0.1" name="sausage[70]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="olive">Олів'є</label><input type="number" step="0.1" name="sausage[71]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="molochna-gocha">Молочна ДСТУ(Гоща)</label><input type="number" step="0.1" name="sausage[72]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="posolska-gocha">Посольська вар.(Гоща)</label><input type="number" step="0.1" name="sausage[73]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="serdelka-ukr">Сарделька українська</label><input type="number" step="0.1" name="sausage[74]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="serdelka-tovstunchik">Сарделька "Товстунчик"</label><input type="number" step="0.1" name="sausage[75]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="serdelka-shkilna">Сарделька "Шкільна"</label><input type="number" step="0.1" name="sausage[76]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="serdelka-mocarela">Сарделька "Моцарела"</label><input type="number" step="0.1" name="sausage[77]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="sosiska-lasunya">Сосиска "Ласуня"</label><input type="number" step="0.1" name="sausage[78]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="sosiska-lakomka">Сосиска "Лакомка"</label><input type="number" step="0.1" name="sausage[79]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="krakivska-brashno">Краківська (Брашно)</label><input type="number" step="0.1" name="sausage[80]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="shpikachka">Шпикачка</label><input type="number" step="0.1" name="sausage[81]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="dovbushska-brashno">Довбушська (Брашно)</label><input type="number" step="0.1" name="sausage[82]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="furshetna-gayar">Фуршетна (Гаяр)</label><input type="number" step="0.1" name="sausage[83]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="furshetna-brashno">Фуршетна (Брашно)</label><input type="number" step="0.1" name="sausage[84]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="servilat">Сервілат царський</label><input type="number" step="0.1" name="sausage[85]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="posolska-stema">Посольська (Стема)</label><input type="number" step="0.1" name="sausage[86]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="firmova-stema">Фірмова (Стема)</label><input type="number" step="0.1" name="sausage[87]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="salyami-italy">Салямі італійська</label><input type="number" step="0.1" name="sausage[88]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="svyatkova-stema">Святкова (Стема)</label><input type="number" step="0.1" name="sausage[89]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="balikova">Баликова</label><input type="number" step="0.1" name="sausage[90]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="mislivski">Мисливські</label><input type="number" step="0.1" name="sausage[91]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="domnadrovah">Домашня на дровах</label><input type="number" step="0.1" name="sausage[92]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="moskovska-gorodok">Московська (Городок)</label><input type="number" step="0.1" name="sausage[93]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="moskovska-stema">Московська (Стема)</label><input type="number" step="0.1" name="sausage[94]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="moskovska-dstu">Московська ДСТУ</label><input type="number" step="0.1" name="sausage[95]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="zamkova">Замкова</label><input type="number" step="0.1" name="sausage[96]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="staroslovyanska">Старослов'янська</label><input type="number" step="0.1" name="sausage[97]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="uzhgorodska">Ужгородська</label><input type="number" step="0.1" name="sausage[98]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="avstraliyska">Австралійська</label><input type="number" step="0.1" name="sausage[99]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="bochok-polsha">Бочок (Польща)</label><input type="number" step="0.1" name="sausage[100]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="mahan">Махан</label><input type="number" step="0.1" name="sausage[101]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="macik">Мацик</label><input type="number" step="0.1" name="sausage[102]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="sloyka">Слойка</label><input type="number" step="0.1" name="sausage[103]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="sneki">Снеки до пива</label><input type="number" step="0.1" name="sausage[104]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="myunhenski-white">Мюнхенські білі</label><input type="number" step="0.1" name="sausage[105]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="furshetna-stasyuk">Фуршетна (Стасюк)</label><input type="number" step="0.1" name="sausage[106]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="drogobicka-stasyuk">Дрогобицька (Стасюк)</label><input type="number" step="0.1" name="sausage[107]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="guculska-stasyuk">Гуцульська (Стасюк)</label><input type="number" step="0.1" name="sausage[108]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="domnadrovah-stasyuk">Дом. на дровах (Стасюк)</label><input type="number" step="0.1" name="sausage[109]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="moskovska-stasyuk">Московська (Стасюк)</label><input type="number" step="0.1" name="sausage[110]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="mislivski-stasyuk">Мисливські (Стасюк)</label><input type="number" step="0.1" name="sausage[111]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="muskatna-stasyuk">Мускатна (Стасюк)</label><input type="number" step="0.1" name="sausage[112]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="shashlichni-stasyuk">Шашличні (Стасюк)</label><input type="number" step="0.1" name="sausage[113]"  placeholder=" Кількість">
					</li>
				</ul>
				<h2>Сир</h2>
				<ul>
					<li>
						<label for="sir-serenada">Сир "Серенада"</label><input type="number" step="0.1" name="cheese[114]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="sir-yellow">Сир "Жовтий"</label><input type="number" step="0.1" name="cheese[115]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="mocarela-black">Сир "Моцарела"(чорний)</label><input type="number" step="0.1" name="cheese[116]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="mocarela-green">Сир "Моцарела"(зелений)</label><input type="number" step="0.1" name="cheese[117]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="mocarela-long">Сир "Моцарела"(довгий)</label><input type="number" step="0.1" name="cheese[118]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="sir-king">Сир "Королівський"</label><input type="number" step="0.1" name="cheese[119]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="sir-favita">Сир "Фавіта"</label><input type="number" step="0.1" name="cheese[120]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="sir-slayen">Сир "Слайен"</label><input type="number" step="0.1" name="cheese[121]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="sir-topleniy">Сир "Топльоний"</label><input type="number" step="0.1" name="cheese[122]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="sirki-timosha">Сирки "Тімоша"</label><input type="number" step="0.1" name="cheese[123]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="maslo-minske">Масло "Мінське"</label><input type="number" step="0.1" name="cheese[124]"  placeholder=" Кількість">
					</li>
				</ul>
				<h2>Рибна переробка</h2>
				<ul>
					<li>
						<label for="oseledec-ss">Оселедець с/с</label><input type="number" step="0.1" name="fish_processing[125]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="skumbriya-ss">Скумбрія с/с</label><input type="number" step="0.1" name="fish_processing[126]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="fileoseledcya-ss">Філе оселедця с/с</label><input type="number" step="0.1" name="fish_processing[127]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="tornado-skumbriya">Торнадо скумбрія</label><input type="number" step="0.1" name="fish_processing[128]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="tyulka-oil">Тюлька в олії</label><input type="number" step="0.1" name="fish_processing[129]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="tyulka-baltiyska">Тюлька балтійська</label><input type="number" step="0.1" name="fish_processing[130]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="oseledec-goroh">Оселедець (горох)</label><input type="number" step="0.1" name="fish_processing[131]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="salaka-oil">Салака в олії</label><input type="number" step="0.1" name="fish_processing[132]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="shproty-oil">Шпроти в олії</label><input type="number" step="0.1" name="fish_processing[133]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="gorbusha">Горбуша кусок</label><input type="number" step="0.1" name="fish_processing[134]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="midiya">Мідія</label><input type="number" step="0.1" name="fish_processing[135]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="skumbriya-oil">Скумбрія в олії</label><input type="number" step="0.1" name="fish_processing[136]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="morkva-king">Морква по кор.</label><input type="number" step="0.1" name="fish_processing[137]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="salat-shanhai">Салат "Шанхай"</label><input type="number" step="0.1" name="fish_processing[138]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="salat-babinelito">Салат "Бабине літо"</label><input type="number" step="0.1" name="fish_processing[139]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="morska-cibulya">Морська з цибулею</label><input type="number" step="0.1" name="fish_processing[140]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="morska-morkva">Морська з морквою</label><input type="number" step="0.1" name="fish_processing[141]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="skumbriya-hk">Скумбрія х/к</label><input type="number" step="0.1" name="fish_processing[142]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="skumbriya-gk">Скумбрія г/к</label><input type="number" step="0.1" name="fish_processing[143]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="fileskumbr-hk">Філе скумбр. х/к</label><input type="number" step="0.1" name="fish_processing[144]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="fileoseled-hk">Філе оселед. х/к</label><input type="number" step="0.1" name="fish_processing[145]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="sayra-hk">Сайра х/к</label><input type="number" step="0.1" name="fish_processing[146]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="moyva-hk">Мойва х/к</label><input type="number" step="0.1" name="fish_processing[147]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="salaka-hk">Салака х/к</label><input type="number" step="0.1" name="fish_processing[148]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="dunayka">Дунайка</label><input type="number" step="0.1" name="fish_processing[149]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="vomer">Вомер</label><input type="number" step="0.1" name="fish_processing[150]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="tushka-bichka">Тушка бичка</label><input type="number" step="0.1" name="fish_processing[151]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="hrebetlos-hk">Хребет лос. х/к</label><input type="number" step="0.1" name="fish_processing[152]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="hrebetlos-gk">Хребет лос. г/к</label><input type="number" step="0.1" name="fish_processing[153]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="vugor-hk">Вугор х/к</label><input type="number" step="0.1" name="fish_processing[154]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="lyach-vyaleniy">Лящ в'ялений</label><input type="number" step="0.1" name="fish_processing[155]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="okun-vyaleniy">Окунь в'ялений</label><input type="number" step="0.1" name="fish_processing[156]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="chuka-vyalena">Щука в'ялена</label><input type="number" step="0.1" name="fish_processing[157]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="chehon-vyalena">Чехонь в'ялена</label><input type="number" step="0.1" name="fish_processing[158]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="plotva-vyalena">Плотва в'ялена</label><input type="number" step="0.1" name="fish_processing[159]"  placeholder=" Кількість">
					</li>
				</ul>
				<h2>Риба с/м</h2>
				<ul>
					<li>
						<label for="oseledec-sm">Оселедець с/м</label><input type="number" step="0.1" name="fish_sm[160]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="skumbriya-sm">Скумбрія с/м</label><input type="number" step="0.1" name="fish_sm[161]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="hek-sm">Хек с/м</label><input type="number" step="0.1" name="fish_sm[162]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="salaka-sm">Салака с/м</label><input type="number" step="0.1" name="fish_sm[163]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="krevetka">Креветка</label><input type="number" step="0.1" name="fish_sm[164]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="steyk-mas">Стейк масляної</label><input type="number" step="0.1" name="fish_sm[165]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="steyk-los">Стейк лосося</label><input type="number" step="0.1" name="fish_sm[166]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="krevetka-king">Креветка королівська</label><input type="number" step="0.1" name="fish_sm[167]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="file-panhasiusa">Філе пангасіуса</label><input type="number" step="0.1" name="fish_sm[168]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="nototeniya">Нототенія</label><input type="number" step="0.1" name="fish_sm[169]"  placeholder=" Кількість">
					</li>
				</ul>
				<h2>Овіс</h2>
				<ul>
					<li>
						<label for="krupa-yachna">Крупа ячна</label><input type="number" step="0.1" name="ovis[170]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="krupa-pshenichna">Крупа пшенична</label><input type="number" step="0.1" name="ovis[171]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="krupa-kukurudzyana">Крупа кукурудзяна</label><input type="number" step="0.1" name="ovis[172]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="grechka">Гречка</label><input type="number" step="0.1" name="ovis[173]" placeholder=" Кількість">
					</li>
					<li>
						<label for="grechaniy-prodil">Гречаний проділ</label><input type="number" step="0.1" name="ovis[174]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="perlovka">Перловка</label><input type="number" step="0.1" name="ovis[175]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="ris-long">Рис довгий</label><input type="number" step="0.1" name="ovis[176]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="ris-circle">Рис круглий</label><input type="number" step="0.1" name="ovis[177]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="ris-pareniy">Рис парений</label><input type="number" step="0.1" name="ovis[178]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="ris-sichka">Рис січка</label><input type="number" step="0.1" name="ovis[179]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="pshono">Пшоно</label><input type="number" step="0.1" name="ovis[180]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="manka">Манка</label><input type="number" step="0.1" name="ovis[181]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="goroh">Горох</label><input type="number" step="0.1" name="ovis[182]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="arnautka">Арнаутка</label><input type="number" step="0.1" name="ovis[183]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="sil-kam">Сіль кам'яна</label><input type="number" step="0.1" name="ovis[184]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="sil-briket">Сіль в брикеті</label><input type="number" step="0.1" name="ovis[185]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="krohmal">Крохмаль</label><input type="number" step="0.1" name="ovis[186]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="soda-harchova">Сода харчова</label><input type="number" step="0.1" name="ovis[187]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="ocet-lviv">Оцет львівський</label><input type="number" step="0.1" name="ovis[188]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="cukor">Цукор</label><input type="number" step="0.1" name="ovis[189]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="kilka-darinka">Кілька даринка</label><input type="number" step="0.1" name="ovis[190]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="kukurudza-koncerv">Кукурудза коцервов.</label><input type="number" step="0.1" name="ovis[191]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="vermishel-gorodok-3kg">Вермішель городок 3кг</label><input type="number" step="0.1" name="ovis[192]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="vermishel-gorodok-1kg">Вермішель городок 1кг</label><input type="number" step="0.1" name="ovis[193]"  placeholder=" Кількість">
					</li>
				</ul>
				<h2>Радема</h2>
				<ul>
					<li>
						<label for="zernyatko-raf5l">Зернятко раф. 5л</label><input type="number" step="0.1" name="radema[194]" placeholder=" Кількість">
					</li>
					<li>
						<label for="zernyatko-neraf5l">Зернятко не раф. 5л</label><input type="number" step="0.1" name="radema[195]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="zernyatko-raf2l">Зернятко раф. 2л</label><input type="number" step="0.1" name="radema[196]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="zernyatko-raf3l">Зернятко раф. 3л</label><input type="number" step="0.1" name="radema[197]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="zernyatko-raf1l">Зернятко раф. 1л</label><input type="number" step="0.1" name="radema[198]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="zernyatko-neraf1l">Зернятко не раф. 1л</label><input type="number" step="0.1" name="radema[199]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="oil-polsha1l">Олія (Польща)1л</label><input type="number" step="0.1" name="radema[200]"  placeholder=" Кількість">
					</li>
					<li>
						<label for="oil-polsha5l">Олія (Польща)5л</label><input type="number" step="0.1" name="radema[201]"  placeholder=" Кількість">
					</li>
				</ul>
			</div>
			<input type="hidden" name="date" value="<?php echo date('Y-m-d') ?>" />
			<input type="submit" class="sub-save save-dostavka" name="save_dostavka" value="Зберегти">
		</form>
		<?php } ?>
		
	</body>
	</html>
