<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<link rel="stylesheet" href="../styles/authorization.css">
</head>
<body class="delivery">	
	

	<?php 
	$errorsl = $this->get('errorsl');

	if (!isset($_SESSION['login_delivery'])) {            
		?>
		<div class="authorization-delivery">
			<?php if (!empty($errorsl)) { ?>
			<div>
				<span style="color:red	;"><?php echo $errorsl; ?></span>
			</div> 
			<?php } ?>
			<p>Вхід на сторінку доставки</p>
			<br/>
			<form action="<?php echo base_url .'delivery'; ?>" method="post">
				<input class="delivery-int" type="text" name="login" placeholder=" ваш логін" value="<?php echo @$_POST['login']; ?>" /><br/><br/>
				<input class="delivery-int" type="password" name="password" placeholder=" ваш пароль"/><br/><br/>
				<input type="submit" name="log" value="Увійти" />
			</form>
		</div>
		<?php }
		else { ?>

		<div class="delivery-block-menu">
			<span><a href="#">Бочка</a></span>
			<span><a href="#">Рибний термінал</a></span>
			<span><a href="#">Гуртовня</a></span>
			<span><a href="#">Центр</a></span>
			<span><a class="delivery-exit" href="<?php echo base_url .'delivery/logout'; ?>">Вихід</a></span>
		</div>

		<form action="<?php echo base_url .'delivery';?>" method="post">
			<div class="dostavka">	
				<h2>Фрукти</h2>
				<ul>
					<li><input type="checkbox" class="checkbox" id="banan" />
						<label for="banan">Банан</label><input type="number" name="banan" step="0.1" placeholder=" Кількість">
					</li>
					<li>	<input type="checkbox" class="checkbox" id="apelsin" />
						<label for="apelsin">Апeльсин</label><input type="number" step="0.1" name="apelsin" placeholder=" Кількість" >
					</li>
					<li>	<input type="checkbox" class="checkbox" id="limon" />
						<label for="limon">Лимон</label><input type="number" step="0.1" name="limon" placeholder=" Кількість" >
					</li>
					<li>	<input type="checkbox" class="checkbox" id="laim" />
						<label for="laim">Лайм</label><input type="number" step="0.1" name="laim" placeholder=" Кількість" >
					</li>
					<li>	<input type="checkbox" class="checkbox" id="greypfruit" />
						<label for="greypfruit">Грейпфрукт</label><input type="number" step="0.1" name="greypfruit"  placeholder=" Кількість">
					</li>
					<li>	<input type="checkbox" class="checkbox" id="kivi" />
						<label for="kivi">Ківі</label><input type="text" name="kivi" placeholder=" Кількість" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')">
					</li>
					<li>	<input type="checkbox" class="checkbox" id="ananas-big" />
						<label for="ananas-big">Ананас вел.</label><input type="text" name="ananas_big" placeholder=" Кількість" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')">
					</li>
					<li>	<input type="checkbox" class="checkbox" id="ananas-small" />
						<label for="ananas-small">Ананас мал.</label><input type="text" name="ananas_small" placeholder=" Кількість" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')">
					</li>
					<li>	<input type="checkbox" class="checkbox" id="granat" />
						<label for="granat">Гранат</label><input type="text" name="granat" placeholder=" Кількість" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')">
					</li>
					<li>	<input type="checkbox" class="checkbox" id="grusha" />
						<label for="grusha">Груша</label><input type="text" name="grusha" placeholder=" Кількість" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')">
					</li>
					<li>	<input type="checkbox" class="checkbox" id="persik-red" />
						<label for="persik-red">Персик "Редхевен"</label><input type="text" name="persik_red" placeholder=" Кількість" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')">
					</li>
					<li>	<input type="checkbox" class="checkbox" id="persik-princ" />
						<label for="persik-princ">Персик "Принц"</label><input type="text" name="persik_princ" placeholder=" Кількість" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')">
					</li>
					<li>	<input type="checkbox" class="checkbox" id="persik-ingir" />
						<label for="persik-ingir">Персик "Інжирний"</label><input type="text" name="persik_ingir" placeholder=" Кількість" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')">
					</li>		
					<li>	<input type="checkbox" class="checkbox" id="nektarin-white" />
						<label for="nektarin-white">Нектарин "Світлий"</label><input type="text" name="nektarin_white" placeholder=" Кількість" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')">
					</li>
					<li>	<input type="checkbox" class="checkbox" id="nektarin-black" />
						<label for="nektarin-black">Нектарин "Темний"</label><input type="text" name="nektarin_black" placeholder=" Кількість" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')">
					</li>	
					<li>	<input type="checkbox" class="checkbox" id="abrikos" />
						<label for="abrikos">Абрикос</label><input type="text" name="abrikos" placeholder=" Кількість" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')">
					</li>
					<li>	<input type="checkbox" class="checkbox" id="sliva" />
						<label for="sliva">Слива</label><input type="text" name="sliva" placeholder=" Кількість" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')">
					</li>
					<li>	<input type="checkbox" class="checkbox" id="vinograd-kish" />
						<label for="vinograd-kish">Виноград "Киш-Миш"</label><input type="text" name="vinograd_kish" placeholder=" Кількість" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')">
					</li>
					<li>	<input type="checkbox" class="checkbox" id="vinograd-myskat" />
						<label for="vinograd-myskat">Виноград "Мускат"</label><input type="text" name="vinograd_myskat" placeholder=" Кількість" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')">
					</li>
					<li>	<input type="checkbox" class="checkbox" id="vinograd-arkadiya" />
						<label for="vinograd-arkadiya">Виноград "Аркадія"</label><input type="text" name="vinograd_arkadiya" placeholder=" Кількість" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')">
					</li>
					<li>	<input type="checkbox" class="checkbox" id="vinograd-kardinal" />
						<label for="vinograd-kardinal">Виноград "Кардинал"</label><input type="text" name="vinograd_kardinal" placeholder=" Кількість" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')">
					</li>
					<li>	<input type="checkbox" class="checkbox" id="vinograd-preob" />
						<label for="vinograd-preob">Виноград "Преображеніє"</label><input type="text" name="vinograd_preob" placeholder=" Кількість" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')">
					</li>
					<li>	<input type="checkbox" class="checkbox" id="vinograd-moldova" />
						<label for="vinograd-moldova">Виноград "Молдова"</label><input type="text" name="vinograd_moldova" placeholder=" Кількість" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')">
					</li>
					<li>	<input type="checkbox" class="checkbox" id="yabluko" />
						<label for="yabluko">Яблуко "Голден"</label><input type="text" name="yabluko_golden" placeholder=" Кількість" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')">
					</li>
				</ul>
				<h2>Сухофрукти</h2>
				<ul>
					<li><input type="checkbox" class="checkbox" id="izym" />
						<label for="izym">Ізюм</label><input type="text" name="izym" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="chornosliv-vyal" />
						<label for="chornosliv-vyal">Чорнослив в'ялений</label><input type="text" name="chornosliv_vyal" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="kuraga" />
						<label for="kuraga">Курага</label><input type="text" name="kuraga" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="finiki" />
						<label for="finiki">Фініки</label><input type="text" name="finiki" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="ingir" />
						<label for="ingir">Інжир</label><input type="text" name="ingir" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="cukaty" />
						<label for="cukaty">Цукати</label><input type="text" name="cukaty" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="sushka" />
						<label for="sushka">Сушка</label><input type="text" name="sushka" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>		
				</ul>
				<h2>Овочі</h2>
				<ul>
					<li><input type="checkbox" class="checkbox" id="grib" />
						<label for="grib">Гриб</label><input type="text" name="grib" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="imbir" />
						<label for="imbir">Імбир</label><input type="text" name="imbir" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="ogirok-kornishok" />
						<label for="ogirok-kornishok">Огірок "Корнішок"</label><input type="text" name="ogirok_kornishok" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="krip" />
						<label for="krip">Кріп</label><input type="text" name="krip" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="petrushka" />
						<label for="petrushka">Петрушка</label><input type="text" name="petrushka" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="salat-green" />
						<label for="salat-green">Салат зелений</label><input type="text" name="salat_green" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="avokado" />
						<label for="avokado">Авокадо</label><input type="text" name="avokado" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="ayzberg" />
						<label for="ayzberg">Айзберг</label><input type="text" name="ayzberg" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="rukola" />
						<label for="rukola">Рукола</label><input type="text" name="rukola" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="pomidor-krug" />
						<label for="pomidor-krug">Помідор "Круглий"</label><input type="text" name="pomidor_krug" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="pomidor-sliva" />
						<label for="pomidor-sliva">Помідор "Сливочка"</label><input type="text" name="pomidor_sliva" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="pomidor-yellow" />
						<label for="pomidor-yellow">Помідор жовтий</label><input type="text" name="pomidor_yellow" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="pomidor-red" />
						<label for="pomidor-red">Помідор червоний</label><input type="text" name="pomidor_red" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="pomidor-blackprinc" />
						<label for="pomidor-blackprinc">Помідор "Чорний принц"</label><input type="text" name="pomidor_blackprinc" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="pomidor-sokal" />
						<label for="pomidor-sokal">Помідор "Сокаль"</label><input type="text" name="pomidor_sokal" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="pomidor-zorya" />
						<label for="pomidor-zorya">Помідор "Зоря"</label><input type="text" name="pomidor_zorya" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="pomidor-cheri" />
						<label for="pomidor-cheri">Помідор "Чері"</label><input type="text" name="pomidor_cheri" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="pomidor-kokteyl" />
						<label for="pomidor-kokteyl">Помідор "Коктейль"</label><input type="text" name="pomidor_kokteyl" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="baklazhan" />
						<label for="baklazhan">Баклажан</label><input type="text" name="baklazhan" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="perec-herson" />
						<label for="perec-herson">Перець херсон</label><input type="text" name="perec_herson" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="perec-red" />
						<label for="perec-red">Перець червоний</label><input type="text" name="perec_red" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="perec-yellow" />
						<label for="perec-yellow">Перець жовтий</label><input type="text" name="perec_yellow" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="chasnik" />
						<label for="chasnik">Часник</label><input type="text" name="chasnik" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="kapusta-bilock" />
						<label for="kapusta-bilock">Капуста "Білок."</label><input type="text" name="kapusta_bilock" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="kapusta-cvitna" />
						<label for="kapusta-cvitna">Капуста "Цвітна"</label><input type="text" name="kapusta_cvitna" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="kapusta-pekinska" />
						<label for="kapusta-pekinska">Капуста "Пекінська"</label><input type="text" name="kapusta_pekinska" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="kapusta-brokoli" />
						<label for="kapusta-brokoli">Капуста "Броколі"</label><input type="text" name="kapusta_brokoli" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="morkva" />
						<label for="morkva">Морква</label><input type="text" name="morkva" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="kartoplya" />
						<label for="kartoplya">Картопля</label><input type="text" name="kartoplya" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="buryak" />
						<label for="buryak">Буряк</label><input type="text" name="buryak" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="cibulya" />
						<label for="cibulya">Цибуля</label><input type="text" name="cibulya" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="perec-chili" />
						<label for="perec-chili">Перець чилі</label><input type="text" name="perec_chili" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="cibulya-yalta" />
						<label for="cibulya-yalta">Цибуля "Ялта"</label><input type="text" name="cibulya_yalta" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="cibulya-white" />
						<label for="cibulya-white">Цибуля біла</label><input type="text" name="cibulya_white" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>				
				</ul>
				<h2>Ковбаса</h2>
				<ul>
					<li><input type="checkbox" class="checkbox" id="soyuzna" />
						<label for="soyuzna">Союзна</label><input type="text" name="soyuzna" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="originalna" />
						<label for="originalna">Оригінальна</label><input type="text" name="originalna" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="minska" />
						<label for="minska">Мінська</label><input type="text" name="minska" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="ryadyanska" />
						<label for="ryadyanska">Радянська</label><input type="text" name="ryadyanska" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="ekstra" />
						<label for="ekstra">Екстра</label><input type="text" name="ekstra" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="olive" />
						<label for="olive">Олів'є</label><input type="text" name="olive" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="molochna-gocha" />
						<label for="molochna-gocha">Молочна ДСТУ(Гоща)</label><input type="text" name="molochna_gocha" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="posolska-gocha" />
						<label for="posolska-gocha">Посольська вар.(Гоща)</label><input type="text" name="posolska_gocha" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="serdelka-ukr" />
						<label for="serdelka-ukr">Сарделька українська</label><input type="text" name="serdelka_ukr" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="serdelka-tovstunchik" />
						<label for="serdelka-tovstunchik">Сарделька "Товстунчик"</label><input type="text" name="serdelka_tovstunchik" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="serdelka-shkilna" />
						<label for="serdelka-shkilna">Сарделька "Шкільна"</label><input type="text" name="serdelka_shkilna" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="serdelka-mocarela" />
						<label for="serdelka-mocarela">Сарделька "Моцарела"</label><input type="text" name="serdelka_mocarela" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="sosiska-lasunya" />
						<label for="sosiska-lasunya">Сосиска "Ласуня"</label><input type="text" name="sosiska_lasunya" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="sosiska-lakomka" />
						<label for="sosiska-lakomka">Сосиска "Лакомка"</label><input type="text" name="sosiska_lakomka" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="krakivska-brashno" />
						<label for="krakivska-brashno">Краківська (Брашно)</label><input type="text" name="krakivska_brashno" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="shpikachka" />
						<label for="shpikachka">Шпикачка</label><input type="text" name="shpikachka" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="dovbushska-brashno" />
						<label for="dovbushska-brashno">Довбушська (Брашно)</label><input type="text" name="dovbushska_brashno" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="furshetna-gayar" />
						<label for="furshetna-gayar">Фуршетна (Гаяр)</label><input type="text" name="furshetna_gayar" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="furshetna-brashno" />
						<label for="furshetna-brashno">Фуршетна (Брашно)</label><input type="text" name="furshetna_brashno" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="servilat" />
						<label for="servilat">Сервілат царський</label><input type="text" name="servilat" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="posolska-stema" />
						<label for="posolska-stema">Посольська (Стема)</label><input type="text" name="posolska_stema" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="firmova-stema" />
						<label for="firmova-stema">Фірмова (Стема)</label><input type="text" name="firmova_stema" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="salyami-italy" />
						<label for="salyami-italy">Салямі італійська</label><input type="text" name="salyami_italy" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="svyatkova-stema" />
						<label for="svyatkova-stema">Святкова (Стема)</label><input type="text" name="svyatkova_stema" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="balikova" />
						<label for="balikova">Баликова</label><input type="text" name="balikova" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="mislivski" />
						<label for="mislivski">Мисливські</label><input type="text" name="mislivski" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="domnadrovah" />
						<label for="domnadrovah">Домашня на дровах</label><input type="text" name="domnadrovah" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="moskovska-gorodok" />
						<label for="moskovska-gorodok">Московська (Городок)</label><input type="text" name="moskovska_gorodok" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="moskovska-stema" />
						<label for="moskovska-stema">Московська (Стема)</label><input type="text" name="moskovska_stema" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="moskovska-dstu" />
						<label for="moskovska-dstu">Московська ДСТУ</label><input type="text" name="moskovska_dstu" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="zamkova" />
						<label for="zamkova">Замкова</label><input type="text" name="zamkova" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="staroslovyanska" />
						<label for="staroslovyanska">Старослов'янська</label><input type="text" name="staroslovyanska" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="uzhgorodska" />
						<label for="uzhgorodska">Ужгородська</label><input type="text" name="uzhgorodska" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="avstraliyska" />
						<label for="avstraliyska">Австралійська</label><input type="text" name="avstraliyska" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="bochok-polsha" />
						<label for="bochok-polsha">Бочок (Польща)</label><input type="text" name="bochok_polsha" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="mahan" />
						<label for="mahan">Махан</label><input type="text" name="mahan" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="macik" />
						<label for="macik">Мацик</label><input type="text" name="macik" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="sloyka" />
						<label for="sloyka">Слойка</label><input type="text" name="sloyka" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="sneki" />
						<label for="sneki">Снеки до пива</label><input type="text" name="sneki" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="myunhenski-white" />
						<label for="myunhenski-white">Мюнхенські білі</label><input type="text" name="myunhenski_white" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="furshetna-stasyuk" />
						<label for="furshetna-stasyuk">Фуршетна (Стасюк)</label><input type="text" name="furshetna_stasyuk" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="drogobicka-stasyuk" />
						<label for="drogobicka-stasyuk">Дрогобицька (Стасюк)</label><input type="text" name="drogobicka_stasyuk" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="guculska-stasyuk" />
						<label for="guculska-stasyuk">Гуцульська (Стасюк)</label><input type="text" name="guculska_stasyuk" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="domnadrovah-stasyuk" />
						<label for="domnadrovah-stasyuk">Дом. на дровах (Стасюк)</label><input type="text" name="domnadrovah_stasyuk" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="moskovska-stasyuk" />
						<label for="moskovska-stasyuk">Московська (Стасюк)</label><input type="text" name="moskovska_stasyuk" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="mislivski-stasyuk" />
						<label for="mislivski-stasyuk">Мисливські (Стасюк)</label><input type="text" name="mislivski_stasyuk" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="muskatna-stasyuk" />
						<label for="muskatna-stasyuk">Мускатна (Стасюк)</label><input type="text" name="muskatna_stasyuk" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="shashlichni-stasyuk" />
						<label for="shashlichni-stasyuk">Шашличні (Стасюк)</label><input type="text" name="shashlichni_stasyuk" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
				</ul>
				<h2>Сир</h2>
				<ul>
					<li><input type="checkbox" class="checkbox" id="sir-serenada" />
						<label for="sir-serenada">Сир "Серенада"</label><input type="text" name="sir_serenada" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="sir-yellow" />
						<label for="sir-yellow">Сир "Жовтий"</label><input type="text" name="sir_yellow" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="mocarela-black" />
						<label for="mocarela-black">Сир "Моцарела"(чорний)</label><input type="text" name="mocarela_black" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="mocarela-green" />
						<label for="mocarela-green">Сир "Моцарела"(зелений)</label><input type="text" name="mocarela_green" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="mocarela-long" />
						<label for="mocarela-long">Сир "Моцарела"(довгий)</label><input type="text" name="mocarela_long" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="sir-king" />
						<label for="sir-king">Сир "Королівський"</label><input type="text" name="sir_king" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="sir-favita" />
						<label for="sir-favita">Сир "Фавіта"</label><input type="text" name="sir_favita" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="sir-slayen" />
						<label for="sir-slayen">Сир "Слайен"</label><input type="text" name="sir_slayen" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="sir-topleniy" />
						<label for="sir-topleniy">Сир "Топльоний"</label><input type="text" name="sir_topleniy" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="sirki-timosha" />
						<label for="sirki-timosha">Сирки "Тімоша"</label><input type="text" name="sirki_timosha" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="maslo-minske" />
						<label for="maslo-minske">Масло "Мінське"</label><input type="text" name="maslo_minske" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
				</ul>
				<h2>Рибна переробка</h2>
				<ul>
					<li><input type="checkbox" class="checkbox" id="oseledec-ss" />
						<label for="oseledec-ss">Оселедець с/с</label><input type="text" name="oseledec_ss" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="skumbriya-ss" />
						<label for="skumbriya-ss">Скумбрія с/с</label><input type="text" name="skumbriya_ss" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="fileoseledcya-ss" />
						<label for="fileoseledcya-ss">Філе оселедця с/с</label><input type="text" name="fileoseledcya_ss" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="tornado-skumbriya" />
						<label for="tornado-skumbriya">Торнадо скумбрія</label><input type="text" name="tornado_skumbriya" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="tyulka-oil" />
						<label for="tyulka-oil">Тюлька в олії</label><input type="text" name="tyulka_oil" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="tyulka-baltiyska" />
						<label for="tyulka-baltiyska">Тюлька балтійська</label><input type="text" name="tyulka_baltiyska" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="oseledec-goroh" />
						<label for="oseledec-goroh">Оселедець (горох)</label><input type="text" name="oseledec_goroh" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="salaka-oil" />
						<label for="salaka-oil">Салака в олії</label><input type="text" name="salaka_oil" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="shproty-oil" />
						<label for="shproty-oil">Шпроти в олії</label><input type="text" name="shproty_oil" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="gorbusha" />
						<label for="gorbusha">Горбуша кусок</label><input type="text" name="gorbusha" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="midiya" />
						<label for="midiya">Мідія</label><input type="text" name="midiya" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="skumbriya-oil" />
						<label for="skumbriya-oil">Скумбрія в олії</label><input type="text" name="skumbriya_oil" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="morkva-king" />
						<label for="morkva-king">Морква по кор.</label><input type="text" name="morkva_king" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="salat-shanhai" />
						<label for="salat-shanhai">Салат "Шанхай"</label><input type="text" name="salat_shanhai" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="salat-babinelito" />
						<label for="salat-babinelito">Салат "Бабине літо"</label><input type="text" name="salat_babinelito" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="morska-cibulya" />
						<label for="morska-cibulya">Морська з цибулею</label><input type="text" name="morska_cibulya" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="morska-morkva" />
						<label for="morska-morkva">Морська з морквою</label><input type="text" name="morska_morkva" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="skumbriya-hk" />
						<label for="skumbriya-hk">Скумбрія х/к</label><input type="text" name="skumbriya_hk" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="skumbriya-gk" />
						<label for="skumbriya-gk">Скумбрія г/к</label><input type="text" name="skumbriya_gk" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="fileskumbr-hk" />
						<label for="fileskumbr-hk">Філе скумбр. х/к</label><input type="text" name="fileskumbr_hk" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="fileoseled-hk" />
						<label for="fileoseled-hk">Філе оселед. х/к</label><input type="text" name="fileoseled_hk" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="sayra-hk" />
						<label for="sayra-hk">Сайра х/к</label><input type="text" name="sayra_hk" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="moyva-hk" />
						<label for="moyva-hk">Мойва х/к</label><input type="text" name="moyva_hk" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="salaka-hk" />
						<label for="salaka-hk">Салака х/к</label><input type="text" name="salaka_hk" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="dunayka" />
						<label for="dunayka">Дунайка</label><input type="text" name="dunayka" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="vomer" />
						<label for="vomer">Вомер</label><input type="text" name="vomer" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="tushka-bichka" />
						<label for="tushka-bichka">Тушка бичка</label><input type="text" name="tushka_bichka" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="hrebetlos-hk" />
						<label for="hrebetlos-hk">Хребет лос. х/к</label><input type="text" name="hrebetlos_hk" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="hrebetlos-gk" />
						<label for="hrebetlos-gk">Хребет лос. г/к</label><input type="text" name="hrebetlos_gk" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="vugor-hk" />
						<label for="vugor-hk">Вугор х/к</label><input type="text" name="vugor_hk" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="lyach-vyaleniy" />
						<label for="lyach-vyaleniy">Лящ в'ялений</label><input type="text" name="lyach_vyaleniy" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="okun-vyaleniy" />
						<label for="okun-vyaleniy">Окунь в'ялений</label><input type="text" name="okun_vyaleniy" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="chuka-vyalena" />
						<label for="chuka-vyalena">Щука в'ялена</label><input type="text" name="chuka_vyalena" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="chehon-vyalena" />
						<label for="chehon-vyalena">Чехонь в'ялена</label><input type="text" name="chehon_vyalena" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="plotva-vyalena" />
						<label for="plotva-vyalena">Плотва в'ялена</label><input type="text" name="plotva_vyalena" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
				</ul>
				<h2>Риба с/м</h2>
				<ul>
					<li><input type="checkbox" class="checkbox" id="oseledec-sm" />
						<label for="oseledec-sm">Оселедець с/м</label><input type="text" name="oseledec_sm" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="skumbriya-sm" />
						<label for="skumbriya-sm">Скумбрія с/м</label><input type="text" name="skumbriya_sm" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="hek-sm" />
						<label for="hek-sm">Хек с/м</label><input type="text" name="hek_sm" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="salaka-sm" />
						<label for="salaka-sm">Салака с/м</label><input type="text" name="salaka_sm" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="krevetka" />
						<label for="krevetka">Креветка</label><input type="text" name="krevetka" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="steyk-mas" />
						<label for="steyk-mas">Стейк масляної</label><input type="text" name="steyk_mas" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="steyk-los" />
						<label for="steyk-los">Стейк лосося</label><input type="text" name="steyk_los" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="krevetka-king" />
						<label for="krevetka-king">Креветка королівська</label><input type="text" name="krevetka_king" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="file-panhasiusa" />
						<label for="file-panhasiusa">Філе пангасіуса</label><input type="text" name="file_panhasiusa" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="nototeniya" />
						<label for="nototeniya">Нототенія</label><input type="text" name="nototeniya" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
				</ul>
				<h2>Овіс</h2>
				<ul>
					<li><input type="checkbox" class="checkbox" id="krupa-yachna" />
						<label for="krupa-yachna">Крупа ячна</label><input type="text" name="krupa_yachna" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="krupa-pshenichna" />
						<label for="krupa-pshenichna">Крупа пшенична</label><input type="text" name="krupa_pshenichna" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="krupa-kukurudzyana" />
						<label for="krupa-kukurudzyana">Крупа кукурудзяна</label><input type="text" name="krupa_kukurudzyana" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="grechka" />
						<label for="grechka">Гречка</label><input type="text" name="grechka" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="grechaniy-prodil" />
						<label for="grechaniy-prodil">Гречаний проділ</label><input type="text" name="grechaniy_prodil" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="perlovka" />
						<label for="perlovka">Перловка</label><input type="text" name="perlovka" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="ris-long" />
						<label for="ris-long">Рис довгий</label><input type="text" name="ris_long" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="ris-circle" />
						<label for="ris-circle">Рис круглий</label><input type="text" name="ris_circle" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="ris-pareniy" />
						<label for="ris-pareniy">Рис парений</label><input type="text" name="ris_pareniy" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="ris-sichka" />
						<label for="ris-sichka">Рис січка</label><input type="text" name="ris_sichka" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="pshono" />
						<label for="pshono">Пшоно</label><input type="text" name="pshono" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="manka" />
						<label for="manka">Манка</label><input type="text" name="manka" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="goroh" />
						<label for="goroh">Горох</label><input type="text" name="goroh" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="arnautka" />
						<label for="arnautka">Арнаутка</label><input type="text" name="arnautka" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="sil-kam" />
						<label for="sil-kam">Сіль кам'яна</label><input type="text" name="sil_kam" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="sil-briket" />
						<label for="sil-briket">Сіль в брикеті</label><input type="text" name="sil_briket" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="krohmal" />
						<label for="krohmal">Крохмаль</label><input type="text" name="krohmal" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="soda-harchova" />
						<label for="soda-harchova">Сода харчова</label><input type="text" name="soda_harchova" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="ocet-lviv" />
						<label for="ocet-lviv">Оцет львівський</label><input type="text" name="ocet_lviv" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="cukor" />
						<label for="cukor">Цукор</label><input type="text" name="cukor" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="kilka-darinka" />
						<label for="kilka-darinka">Кілька даринка</label><input type="text" name="kilka_darinka" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="kukurudza-koncerv" />
						<label for="kukurudza-koncerv">Кукурудза коцервов.</label><input type="text" name="kukurudza_koncerv" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="vermishel-gorodok-3kg" />
						<label for="vermishel-gorodok-3kg">Вермішель городок 3кг</label><input type="text" name="vermishel_gorodok_3kg" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="vermishel-gorodok-1kg" />
						<label for="vermishel-gorodok-1kg">Вермішель городок 1кг</label><input type="text" name="vermishel_gorodok_1kg" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
				</ul>
				<h2>Радема</h2>
				<ul>
					<li><input type="checkbox" class="checkbox" id="zernyatko-raf5l" />
						<label for="zernyatko-raf5l">Зернятко раф. 5л</label><input type="text" name="zernyatko_raf5l" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="zernyatko-neraf5l" />
						<label for="zernyatko-neraf5l">Зернятко не раф. 5л</label><input type="text" name="zernyatko_neraf5l" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="zernyatko-raf2l" />
						<label for="zernyatko-raf2l">Зернятко раф. 2л</label><input type="text" name="zernyatko_raf2l" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="zernyatko-raf3l" />
						<label for="zernyatko-raf3l">Зернятко раф. 3л</label><input type="text" name="zernyatko_raf3l" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="zernyatko-raf1l" />
						<label for="zernyatko-raf1l">Зернятко раф. 1л</label><input type="text" name="zernyatko_raf1l" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="zernyatko-neraf1l" />
						<label for="zernyatko-neraf1l">Зернятко не раф. 1л</label><input type="text" name="zernyatko_neraf1l" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="oil-polsha1l" />
						<label for="oil-polsha1l">Олія (Польща)1л</label><input type="text" name="oil_polsha1l" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="checkbox" class="checkbox" id="oil-polsha5l" />
						<label for="oil-polsha5l">Олія (Польща)5л</label><input type="text" name="oil_polsha5l" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder=" Кількість">
					</li>
					<li><input type="submit" class="sub-save save-dostavka" name="save_dostavka" value="Зберегти"></li>
				</ul>
			</div>
			<input type="hidden" name="date" value="<?php echo date('Y-m-d') ?>" />
		</form>
		<?php } ?>
	</body>
	</html>