<?php $current = $_SERVER['REQUEST_URI']; ?>
<div class="head">
	<div class="dostavka-head">
		<a href="<?php echo base_url .'index_authorization/logout';?>">Вихід</a>
	</div>
	<div class="search-head">
		<form action="<?php echo base_url .'search';?>" method="get">
			<input class="search-form srch" type="search" name="search_query" placeholder=" введіть ваш запит"/>
			<input class="search-btn srch" type="submit" name="search" value="знайти" />
		</form>
		
	</div>
	<div class="dostavka-head">
		<a class="<?php if($current == '/delivery' || $current == '/delivery/bochka' || $current == '/delivery/fish_terminal' || $current == '/delivery/gurtovnya' || $current == '/delivery/center'): ?>current<?php endif; ?>" href="<?php echo base_url .'delivery';?>">Доставка</a>
	</div>
	<div class="dostavka-head not-border-right">
		<a class="<?php if($current == '/purchase'): ?>current<?php endif; ?>" href="<?php echo base_url .'purchase';?>">Закупка</a>
	</div>
	<div class="dostavka-head not-border-right">
		<a href="<?php echo base_url .'distribution';?>">Розприділення</a>
	</div>

</div>