<div class="head">
	<div class="search-head">
		<form action="/search" method="get">
			<input class="search-form srch" type="search" name="search_query" placeholder=" введіть ваш запит"/>
			<input class="search-btn srch" type="submit" name="search" value="знайти" />
		</form>
		
	</div>
	<div class="dostavka-head">
		<a href="/delivery">Доставка</a>
	</div>
		<div class="dostavka-head purchase">
		<a href="/purchase">Закупка</a>
	</div>
</div>