<!DOCTYPE html>
<html lang="ua-UA">
    <head>
        <title>{{$title}}</title>
        <meta name="title" content="{{$title}}"/>
		 <meta charset="UTF-8"/>
        {{$headfiles}}
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    </head>
    <body>
        {{$header}}
        {{$menu}}
        {{$content}}
    </body>
</html>