 <!DOCTYPE html>
 <html lang="en">
 <head>
 	<meta charset="UTF-8">
 	<title>Вхід ГБ</title>
 	<link rel="shortcut icon" href="/img/iconka.png" type="image/x-icon">
 	<link rel="stylesheet" href="../styles/authorization.css" media="screen">
 </head>
 <body>
 	    <?php 
    if (!isset($_SESSION['login'])) {            
        ?>
 <div class="authorization-block">
 	<p>Вхід в ГБ</p>
 	<h1><img src="../img/logo.png" alt="Гуртова База"></h1>
 	<form action="/index_authorization" method="post">
 		<input type="text" name="login" placeholder=" ваш логін"/><br/><br/>
 		<input type="password" name="password" placeholder=" ваш пароль"/><br/><br/>
 		<input type="submit" name="log" value="Увійти" />
 	</form>
 </div>
 <?php }
 else {
 	header("Location: /");
 } ?>
 </body>
 </html>