<?php 
$row = $this->get('row');
$num2 = $this->get('num2');
$query2 = $this->get('query2');
 ?>
	<div class="plus-table">
		<a href="#" class="plus" title="Додати таблицю"><i class="fas fa-plus"></i></a>
	</div>
	<div class="date">
		10 липня 2018  
	</div>



	<div>
		<table>
			<tr class="table-top">
				<td><?php echo $row['kod']; ?></td>
				<td class="width-name"><?php echo $row['name']; ?></td>
				<td><?php echo $row['bochka']; ?></td>
				<td><?php echo $row['fish']; ?></td>
				<td><?php echo $row['gyrtovna']; ?></td>
				<td><?php echo $row['center']; ?></td>
				<td><?php echo $row['bochka2']; ?></td>
				<td><?php echo $row['fish2']; ?></td>
				<td><?php echo $row['gyrtovna2']; ?></td>
				<td><?php echo $row['center2']; ?></td>
				<td><?php echo $row['dostavka']; ?></td>
				<td><?php echo $row['dia']; ?></td>
			</tr>
			<?php if ($num2) {
                while ($row = mysqli_fetch_array($query2)) { ?>
			<tr>
				<td><?php echo $row['kod_tovar']; ?></td>
				<td class="width-name"><?php echo $row['name_tovar']; ?></td>
				<td><?php echo $row['bochka_tovar']; ?></td>
				<td><?php echo $row['fish_tovar']; ?></td>
				<td><?php echo $row['gyrtovna_tovar']; ?></td>
				<td><?php echo $row['centr_tovar']; ?></td>
				<td><?php echo $row['bochka2_tovar']; ?></td>
				<td><?php echo $row['fish2_tovar']; ?></td>
				<td><?php echo $row['gyrtovna2_tovar']; ?></td>
				<td><?php echo $row['centr2_tovar']; ?></td>
				<td><?php echo $row['dostavka_tovar']; ?></td>
				<td> <a href="#" class="edit" title="Редагувати"> <i class="fas fa-pen"></i></a> <a href="#" class="delete" title="Видалити"><i class="fas fa-trash-alt"></i></a></td>
			</tr>
			<?php } } ?>
		</table>
<a href="/add">Добавить товар</a>
	</div>
