<div class="content">
	<div class="plus-table">
		<a href="#" class="plus" title="Додати таблицю"><i class="fas fa-plus"></i></a>
	</div>
	<div class="date">
		10 липня 2018  
	</div>



	<div>
		<table>
			<tr class="table-top">
				<td>№</td>
				<td class="width-name">Назва</td>
				<td>Бочка</td>
				<td>Рибний термінал</td>
				<td>Гуртовня</td>
				<td class="border2">Центр</td>
				<td>Бочка</td>
				<td>Рибний термінал</td>
				<td>Гуртовня</td>
				<td>Центр</td>
				<td>Доставка</td>
				<td>Дія</td>
			</tr>
			<tr>
				<td>1</td>
				<td>Банани</td>
				<td>34</td>
				<td>54</td>
				<td>46</td>
				<td class="border2">22</td>
				<td>30</td>
				<td>34</td>
				<td>410</td>
				<td>410</td>
				<td>410</td>
				<td> <a href="#" class="edit" title="Редагувати"> <i class="fas fa-pen"></i></a> <a href="#" class="delete" title="Видалити"><i class="fas fa-trash-alt"></i></a></td>
			</tr>
			<tr>
				<td>2</td>
				<td>Мандарини</td>
				<td>34</td>
				<td>54</td>
				<td>46</td>
				<td>22</td>
				<td>30</td>
				<td>34</td>
				<td>410</td>
				<td>410</td>
				<td>410</td>
				<td> <a href="#" class="edit" title="Редагувати"> <i class="fas fa-pen"></i></a> <a href="#" class="delete" title="Видалити"><i class="fas fa-trash-alt"></i></a></td>
			</tr>

		</table>

	</div>

</div>