<div class="menu">
	<div class="logo">
		<a href="/"><img src="img/logo.png" alt="ГуртоваБаза"></a>
	</div>
	<ul class="menu-bar">
		<li class="border-top"><a href="/vegetables">Овочі</a></li>
		<li><a href="/fruits">Фрукти</a></li>
		<li><a href="/sausage">Ковбаса</a></li>
		<li><a href="/fish_sm">Риба С/М</a></li>
		<li><a href="/remake">Переробка</a></li>
		<li><a href="/ovis">Овіс</a></li>
		<li><a href="/radema">Радема</a></li>
	</ul>
</div>