<div style="text-align: center; margin-top: 200px;">
	<p><i style="color: #000; font-size: 30px;" class="fas fa-wrench"></i></p>
	На даний момент ця сторінка в розробці </br>
	<h3>Очікуйте...</h3>
</div>


<!-- <div class="purchase">
	<table>
		<h2>Фрукти</h2>
		<tr class="table-top">
			<td>Назва</td> 
			<td>Кількість ящиків</td>
		</tr>
		<tr>
			<td>Банани</td> 
			<td></td>
		</tr>
		<tr>
			<td>Апельсин</td>
			<td></td>
		</tr>
		<tr>
			<td>Лимон</td>
			<td></td>
		</tr>
		<tr>
			<td>Лайм</td>
			<td></td>
		</tr>
		<tr>
			<td>Грейпфрукт</td>
			<td></td>
		</tr>
		<tr>
			<td>Ківі</td>
			<td></td>
		</tr>
		<tr>
			<td>Ананас вел.</td>
			<td></td>
		</tr>
		<tr>
			<td>Ананас мал.</td>
			<td></td>
		</tr>
		<tr>
			<td>Гранат</td>
			<td></td>
		</tr>
		<tr>
			<td>Груша</td>
			<td></td>
		</tr>
		<tr>
			<td>Персик "Редхевен"</td>
			<td></td>
		</tr>
		<tr>
			<td>Персик "Принц"</td>
			<td></td>
		</tr>
		<tr>
			<td>Персик "Інжирний"</td>
			<td></td>
		</tr>
		<tr>
			<td>Нектарин "Світлий"</td>
			<td></td>
		</tr>
		<tr>
			<td>Нектарин "Темний"</td>
			<td></td>
		</tr>
		<tr>
			<td>Абрикос</td>
			<td></td>
		</tr>
		<tr>
			<td>Слива</td>
			<td></td>
		</tr>
		<tr>
			<td>Виноград "Киш-Миш"</td>
			<td></td>
		</tr>
		<tr>
			<td>Виноград "Мускат"</td>
			<td></td>
		</tr>
		<tr>
			<td>Виноград "Аркадія"</td>
			<td></td>
		</tr>
		<tr>
			<td>Виноград "Кардинал"</td>
			<td></td>
		</tr>
		<tr>
			<td>Виноград "Преображеніє"</td>
			<td></td>
		</tr>
		<tr>
			<td>Виноград "Молдова"</td>
			<td></td>
		</tr>
		<tr>
			<td>Яблуко "Голден"</td>
			<td></td>
		</tr>
		<tr>
			<td>Ізюм</td>
			<td></td>
		</tr>
		<tr>
			<td>Чорнослив в'ялений</td>
			<td></td>
		</tr>
		<tr>
			<td>Курага</td>
			<td></td>
		</tr>
		<tr>
			<td>Фінікі</td>
			<td></td>
		</tr>
		<tr>
			<td>Інжир</td>
			<td></td>
		</tr>
		<tr>
			<td>Цукати</td>
			<td></td>
		</tr>
		<tr>
			<td>Сушка</td>
			<td></td>
		</tr>
	</table>
	<table>
	<h2>Овочі</h2>	
		<tr class="table-top">
			<td>Назва</td>
			<td>Кількість ящиків</td>
		</tr>
		<tr>
			<td>Гриб</td>
			<td></td>
		</tr>
		<tr>
			<td>Імбир</td>
			<td></td>
		</tr>
		<tr>
			<td>Огірок "Корнішок"</td>
			<td></td>
		</tr>
		<tr>
			<td>Кріп</td>
			<td></td>
		</tr>
		<tr>
			<td>Петрушка</td>
			<td></td>
		</tr>
		<tr>
			<td>Салат зелений</td>
			<td></td>
		</tr>
		<tr>
			<td>Авокадо</td>
			<td></td>
		</tr>
		<tr>
			<td>Айзберг</td>
			<td></td>
		</tr>
		<tr>
			<td>Рукола</td>
			<td></td>
		</tr>
		<tr>
			<td>Помідор "Круглий"</td>
			<td></td>
		</tr>
		<tr>
			<td>Помідор "Сливочка"</td>
			<td></td>
		</tr>
		<tr>
			<td>Помідор жовтий</td>
			<td></td>
		</tr>
		<tr>
			<td>Помідор червоний</td>
			<td></td>
		</tr>
		<tr>
			<td>Помідор "Чорний принц"</td>
			<td></td>
		</tr>
		<tr>
			<td>Помідор "Сокаль"</td>
			<td></td>
		</tr>
		<tr>
			<td>Помідор "Зоря"</td>
			<td></td>
		</tr>
		<tr>
			<td>Помідор "Чері"</td>
			<td></td>
		</tr>
		<tr>
			<td>Помідор "Коктейль"</td>
			<td></td>
		</tr>
		<tr>
			<td>Баклажан</td>
			<td></td>
		</tr>
		<tr>
			<td>Перець херсон</td>
			<td></td>
		</tr>
		<tr>
			<td>Перець червоний</td>
			<td></td>
		</tr>
		<tr>
			<td>Перець жовтий</td>
			<td></td>
		</tr>
		<tr>
			<td>Часник</td>
			<td></td>
		</tr>
		<tr>
			<td>Капуста білок.</td>
			<td></td>
		</tr>
		<tr>
			<td>Капуста цвітна</td>
			<td></td>
		</tr>
		<tr>
			<td>Капуста "Пекінська"</td>
			<td></td>
		</tr>
		<tr>
			<td>Капуста "Броколі"</td>
			<td></td>
		</tr>
		<tr>
			<td>Морква</td>
			<td></td>
		</tr>
		<tr>
			<td>Картопля</td>
			<td></td>
		</tr>
		<tr>
			<td>Буряк</td>
			<td></td>
		</tr>
		<tr>
			<td>Цибуля</td>
			<td></td>
		</tr>
		<tr>
			<td>Перець чилі</td>
			<td></td>
		</tr>
		<tr>
			<td>Цибуля "Ялта"</td>
			<td></td>
		</tr>
		<tr>
			<td>Цибуля біла</td>
			<td></td>
		</tr>
	</table>
	<table>
		<h2>Ковбаса</h2>
		<tr class="table-top">
			<td>Назва</td>
			<td>Кількість ящиків</td>
		</tr>
		<tr>
			<td>Союзна</td>
			<td></td>
		</tr>
		<tr>
			<td>Оригінальна</td>
			<td></td>
		</tr>
		<tr>
			<td>Мінська</td>
			<td></td>
		</tr>
		<tr>
			<td>Радянська</td>
			<td></td>
		</tr>
		<tr>
			<td>Екстра</td>
			<td></td>
		</tr>
		<tr>
			<td>Олів'є</td>
			<td></td>
		</tr>
		<tr>
			<td>Молочна ДСТУ(Гоща)</td>
			<td></td>
		</tr>
		<tr>
			<td>Посольська вар.(Гоща)</td>
			<td></td>
		</tr>
		<tr>
			<td>Сарделька українська</td>
			<td></td>
		</tr>
		<tr>
			<td>Сарделька "Товстунчик"</td>
			<td></td>
		</tr>
		<tr>
			<td>Сарделька "Шкільна"</td>
			<td></td>
		</tr>
		<tr>
			<td>Сарделька "Моцарела"</td>
			<td></td>
		</tr>
		<tr>
			<td>Сосиска "Ласуня"</td>
			<td></td>
		</tr>
		<tr>
			<td>Сосиска "Лакомка"</td>
			<td></td>
		</tr>
		<tr>
			<td>Краківська(Брашно)</td>
			<td></td>
		</tr>
		<tr>
			<td>Шпикачка</td>
			<td></td>
		</tr>
		<tr>
			<td>Довбушська(Брашно)</td>
			<td></td>
		</tr>
		<tr>
			<td>Фуршетна(Гаяр)</td>
			<td></td>
		</tr>
		<tr>
			<td>Фуршетна(Брашно)</td>
			<td></td>
		</tr>
		<tr>
			<td>Сервілат царський</td>
			<td></td>
		</tr>
		<tr>
			<td>Посольська(Стема)</td>
			<td></td>
		</tr>
		<tr>
			<td>Фірмова(Стема)</td>
			<td></td>
		</tr>
		<tr>
			<td>Салямі італійська</td>
			<td></td>
		</tr>
		<tr>
			<td>Святкова(Стема)</td>
			<td></td>
		</tr>
		<tr>
			<td>Баликова</td>
			<td></td>
		</tr>
		<tr>
			<td>Мисливські</td>
			<td></td>
		</tr>
		<tr>
			<td>Домашня на дровах</td>
			<td></td>
		</tr>
		<tr>
			<td>Московська(Городок)</td>
			<td></td>
		</tr>
		<tr>
			<td>Московська(Стема)</td>
			<td></td>
		</tr>
		<tr>
			<td>Московська ДСТУ</td>
			<td></td>
		</tr>
		<tr>
			<td>Замкова</td>
			<td></td>
		</tr>
		<tr>
			<td>Старослов'янська</td>
			<td></td>
		</tr>
		<tr>
			<td>Ужгородська</td>
			<td></td>
		</tr>
		<tr>
			<td>Австралійська</td>
			<td></td>
		</tr>
		<tr>
			<td>Бочок(Польща)</td>
			<td></td>
		</tr>
		<tr>
			<td>Махан</td>
			<td></td>
		</tr>
		<tr>
			<td>Мацик</td>
			<td></td>
		</tr>
		<tr>
			<td>Слойка</td>
			<td></td>
		</tr>
		<tr>
			<td>Снеки до пива</td>
			<td></td>
		</tr>
		<tr>
			<td>Мюнхенські білі</td>
			<td></td>
		</tr>
		<tr>
			<td>Фуршетна(Стасюк)</td>
			<td></td>
		</tr>
		<tr>
			<td>Дрогобицька(Стасюк)</td>
			<td></td>
		</tr>
		<tr>
			<td>Гуцульська(Стасюк)</td>
			<td></td>
		</tr>
		<tr>
			<td>Дом. на дровах(Стасюк)</td>
			<td></td>
		</tr>
		<tr>
			<td>Московська(Стасюк)</td>
			<td></td>
		</tr>
		<tr>
			<td>Мисливські(Стасюк)</td>
			<td></td>
		</tr>
		<tr>
			<td>Мускатна(Стасюк)</td>
			<td></td>
		</tr>
		<tr>
			<td>Шашличні(Стасюк)</td>
			<td></td>
		</tr>
	</table>
	<table>
		<h2>Сир</h2>
		<tr class="table-top">
			<td>Назва</td>
			<td>Кількість ящиків</td>
		</tr>
		<tr>
			<td>Сир "Серенада"</td>
			<td></td>
		</tr>
		<tr>
			<td>Сир "Жовтий"</td>
			<td></td>
		</tr>
		<tr>
			<td>Сир "Моцарела"(чорний)</td>
			<td></td>
		</tr>
		<tr>
			<td>Сир "Моцарела"(зелений)</td>
			<td></td>
		</tr>
		<tr>
			<td>Сир "Моцарела"(довгий)</td>
			<td></td>
		</tr>
		<tr>
			<td>Сир "Королівський"</td>
			<td></td>
		</tr>
		<tr>
			<td>Сир "Фавіта"</td>
			<td></td>
		</tr>
		<tr>
			<td>Сир "Слайен"</td>
			<td></td>
		</tr>
		<tr>
			<td>Сир "Топльоний"</td>
			<td></td>
		</tr>
		<tr>
			<td>Сирки "Тімоша"</td>
			<td></td>
		</tr>
		<tr>
			<td>Масло "Мінське"</td>
			<td></td>
		</tr>
	</table>
	<table>
		<h2>Рибна переробка</h2>
		<tr class="table-top">
			<td>Назва</td>
			<td>Кількість ящиків</td>
		</tr>
		<tr>
			<td>Оселедець с/с</td>
			<td></td>
		</tr>
		<tr>
			<td>Скумбрія с/с</td>
			<td></td>
		</tr>
		<tr>
			<td>Філе оселедця с/с</td>
			<td></td>
		</tr>
		<tr>
			<td>Торнадо скумбрія</td>
			<td></td>
		</tr>
		<tr>
			<td>Тюлька в олії</td>
			<td></td>
		</tr>
		<tr>
			<td>Тюлька балтійська</td>
			<td></td>
		</tr>
		<tr>
			<td>Оселедець (горох)</td>
			<td></td>
		</tr>
		<tr>
			<td>Салака в олії</td>
			<td></td>
		</tr>
		<tr>
			<td>Шпроти в олії</td>
			<td></td>
		</tr>
		<tr>
			<td>Горбуша кусок</td>
			<td></td>
		</tr>
		<tr>
			<td>Мідія</td>
			<td></td>
		</tr>
		<tr>
			<td>Скумбрія в олії</td>
			<td></td>
		</tr>
		<tr>
			<td>Морква по кор.</td>
			<td></td>
		</tr>
		<tr>
			<td>Салат "Шанхай"</td>
			<td></td>
		</tr>
		<tr>
			<td>Салат "Бабине літо"</td>
			<td></td>
		</tr>
		<tr>
			<td>Морська з цибулею</td>
			<td></td>
		</tr>
		<tr>
			<td>Морська з морквою</td>
			<td></td>
		</tr>
		<tr>
			<td>Скумбрія х/к</td>
			<td></td>
		</tr>
		<tr>
			<td>Скумбрія г/к</td>
			<td></td>
		</tr>
		<tr>
			<td>Філе скумбр. х/к</td>
			<td></td>
		</tr>
		<tr>
			<td>Філе оселед. х/к</td>
			<td></td>
		</tr>
		<tr>
			<td>Сайра х/к</td>
			<td></td>
		</tr>
		<tr>
			<td>Мойва х/к</td>
			<td></td>
		</tr>
		<tr>
			<td>Салака х/к</td>
			<td></td>
		</tr>
		<tr>
			<td>Дунайка</td>
			<td></td>
		</tr>
		<tr>
			<td>Вомер</td>
			<td></td>
		</tr>
		<tr>
			<td>Тушка бичка</td>
			<td></td>
		</tr>
		<tr>
			<td>Хребет лос. х/к</td>
			<td></td>
		</tr>
		<tr>
			<td>Хребет лос. г/к</td>
			<td></td>
		</tr>
		<tr>
			<td>Вугор х/к</td>
			<td></td>
		</tr>
		<tr>
			<td>Лящ в'ялений</td>
			<td></td>
		</tr>
		<tr>
			<td>Окунь в'ялений</td>
			<td></td>
		</tr>
		<tr>
			<td>Щука в'ялена</td>
			<td></td>
		</tr>
		<tr>
			<td>Чехонь в'ялена</td>
			<td></td>
		</tr>
		<tr>
			<td>Плотва в'ялена</td>
			<td></td>
		</tr>
		
	</table>
	<table>
		<h2>Риба с/м</h2>
		<tr class="table-top">
			<td>Назва</td>
			<td>Кількість ящиків</td>
		</tr>
		<tr>
			<td>Оселедець с/м</td>
			<td></td>
		</tr>
		<tr>
			<td>Скумбрія с/м</td>
			<td></td>
		</tr>
		<tr>
			<td>Хек с/м</td>
			<td></td>
		</tr>
		<tr>
			<td>Салака с/м</td>
			<td></td>
		</tr>
		<tr>
			<td>Креветка</td>
			<td></td>
		</tr>
		<tr>
			<td>Стейк масляної</td>
			<td></td>
		</tr>
		<tr>
			<td>Стейк лосося</td>
			<td></td>
		</tr>
		<tr>
			<td>Креветка королівська</td>
			<td></td>
		</tr>
		<tr>
			<td>Філе пангасіуса</td>
			<td></td>
		</tr>
		<tr>
			<td>Нототенія</td>
			<td></td>
		</tr>
	</table>
	<table>
		<h2>Овіс</h2>
		<tr class="table-top">
			<td>Назва</td>
			<td>Кількість ящиків</td>
		</tr>
		<tr>
			<td>Крупа ячна</td>
			<td></td>
		</tr>
		<tr>
			<td>Крупа пшенична</td>
			<td></td>
		</tr>
		<tr>
			<td>Крупа кукурудзяна</td>
			<td></td>
		</tr>
		<tr>
			<td>Гречка</td>
			<td></td>
		</tr>
		<tr>
			<td>Гречаний проділ</td>
			<td></td>
		</tr>
		<tr>
			<td>Перловка</td>
			<td></td>
		</tr>
		<tr>
			<td>Рис довгий</td>
			<td></td>
		</tr>
		<tr>
			<td>Рис круглий</td>
			<td></td>
		</tr>
		<tr>
			<td>Рис січка</td>
			<td></td>
		</tr>
		<tr>
			<td>Пшоно</td>
			<td></td>
		</tr>
		<tr>
			<td>Манка</td>
			<td></td>
		</tr>
		<tr>
			<td>Горох</td>
			<td></td>
		</tr>
		<tr>
			<td>Арнаутка</td>
			<td></td>
		</tr>
		<tr>
			<td>Сіль кам'яна</td>
			<td></td>
		</tr>
		<tr>
			<td>Сіль в брикеті</td>
			<td></td>
		</tr>
		<tr>
			<td>Крохмаль</td>
			<td></td>
		</tr>
		<tr>
			<td>Сода харчова</td>
			<td></td>
		</tr>
		<tr>
			<td>Оцет львівський</td>
			<td></td>
		</tr>
		<tr>
			<td>Цукор</td>
			<td></td>
		</tr>
		<tr>
			<td>Кілька даринка</td>
			<td></td>
		</tr>
		<tr>
			<td>Кукурудза концервов.</td>
			<td></td>
		</tr>
		<tr>
			<td>Вермішель городок 3кг</td>
			<td></td>
		</tr>
		<tr>
			<td>Вермішель городок 1кг</td>
			<td></td>
		</tr>
	</table>
	<table>
		<h2>Радема</h2>
		<tr class="table-top">
			<td>Назва</td>
			<td>Кількість ящиків</td>
		</tr>
		<tr>
			<td>Зернятко раф. 5л</td>
			<td></td>
		</tr>
		<tr>
			<td>Зернятко не раф. 5л</td>
			<td></td>
		</tr>
		<tr>
			<td>Зернятко раф. 2л</td>
			<td></td>
		</tr>
		<tr>
			<td>Зернятко раф. 3л</td>
			<td></td>
		</tr>
		<tr>
			<td>Зернятко раф. 1л</td>
			<td></td>
		</tr>
		<tr>
			<td>Зернятко не раф. 1л</td>
			<td></td>
		</tr>
		<tr>
			<td>Олія(Польща) 1л</td>
			<td></td>
		</tr>
		<tr>
			<td>Олія(Польща) 5л</td>
			<td></td>
		</tr>
	</table>
</div> -->